### ISSUE TITLE
Error with length and subdata SQL

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1022]
Hello,

I work with SQL datalib and multiple subdata, so i have to use the parameter "length". 
My property is defined in library and i put the length at 5.
But when the SQL request returns only 2 rows there is an error : 
![nbrow](https://cloud.githubusercontent.com/assets/18569182/20435426/5bd74734-adac-11e6-9a9c-6b265ca8743a.JPG)

Is it possible to define a Row limit as SQL ? to avoid an error if there is less than 5 rows ?
Thank you

Cerberus Version : 1.1.9-SNAPSHOT

**Comment by vertigo17** [comment]
When you specify the length at 5, Cerberus will consider that the 5 rows are necessary to load the data.
If not enough rows are retreived from SQL, this is considered as unavailable data reporting NA.
This is to secure the %PROP.n.subdata% is correctly replaced until n=5.

As far as I understand, you define a length at 5 but sometimes use only 2 rows ? I suppose property is defined in library and used on test that sometime need 2 rows but sometimes 5.
I suggest you move the property to the expect testcase where you will be able to put the right size.
Another alternative is to create a new parameter to define the max rows to read but that introduce the risk of empty values that will not be replaced. What would be the expected behaviour in case the size is 5 and SQL return 2 and testcase use a property as %PROP.4.subdata%
