### ISSUE TITLE
PE is not working as expected

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1026]
Hi,

PE seems not to be working properly. 
When opening a url page that stays loading in fact the test continues but it fails in the next action.

Examples:
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=39088317
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=38700504

Can you please take a look?

Thanks

**Comment by vertigo17** [comment]
Sorry I was not able to reproduce.
I beleive we reach the limit of this type of feature as the reason of the failure is probably due to key ressource not beeing loaded.

This is the test I made to reproduce:
Open an url that load a async ressource that delay 20 second (I integrated one directly on Cerberus)  
dummy/index1.jsp?asyncdelay=20000
I set the timeout to 10 second.

Here is the result I get:
![selection_165](https://cloud.githubusercontent.com/assets/5342048/21569661/330b7cce-cebf-11e6-9642-68ed74d53406.jpg)

The load of the page stop after the 10s timeout (even if the load is not finished) and next action is proceed correctly.
Next actions are to type a field with a value, submit the form and check on the new page that the value is displayed.
