### ISSUE TITLE
Can't Start Execution / When Parameter "Verbose" set to 1

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#1029]
Cerberus Version : 1.1.9-SNAPSHOT-967

getting that error when Verbose parameter is set to 1 - standard log.
![image](https://cloud.githubusercontent.com/assets/16115517/20568226/13deb3d8-b19c-11e6-8e86-94630f28dc28.png)

It works when set to "0"
Might be "normal". Thing is that before, it did not prevent from launching execution !

Best regards,
PF

**Comment by vertigo17** [comment]
I fixed an issue that prevent the correct error message to be displayed.
With latest version, you should now see the reason why the test cannot be executed.
This is prbably because it failed loading NetExport oor Firebug extention that are necessary when browser is firefox and verbose is >= 1.
Those pluging are used to get the complete trace of http access.
