### ISSUE TITLE
getfromhtml html

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1030]
Hi, when using getfromhtml i tought it returns clean text. But what happens is that if the html text have a <br> the control verifystringcontains will fail with something like:

'VALIDER MON PAIEMENT ET MA COMMANDE' does not contain 'VALIDER MON PAIEMENT ET MA COMMANDE'. 

wich seems a litle bit weird.

http://192.168.134.17/Cerberus/ExecutionDetail.jsp?id_tc=39335343

Could this be changed to return clean text or it is supossed to be like this? 

Thank you!

**Comment by vertigo17** [comment]
OK, I just replace the carriage return by /n string in order to see that invisible character.
It will look like that:

![selection_161](https://cloud.githubusercontent.com/assets/5342048/20608631/d9702342-b283-11e6-80f2-557c2b533a01.jpg)

That should be less confusing.
On the new pages, data are in fields so cariage return should be visible.
@Foudro , if you can confirm and if not, please do the same on the new page.
