### ISSUE TITLE
Being able to assign several labels to several test in one operation

### ISSUE THREAD

**Issue by MichaelWil** [cerberustesting/cerberus-source#1032]
Hi,
We are currently working on labels assigning proper labels to concerned tests.
Currently, in the way it's designed in Cerberus, we have to go in each test to select the concerned labels.

Will it be possible to implement a way to assign several labels to several tests ? 

Feel free to come back to me if any clarifications is required.

Thanks and regards

Michael

**Comment by abourdon** [comment]
Cannot be closed because current implementation is bugged

First, click on select/unselectall buttons from any table's column filter cause page to be reloaded.
As implementation has been copied from the Build Content page, this page also has to be fixed

See #1279 for more details.

Second, label image is not well visible from add and remove tab:

<img width="304" alt="screen shot 2017-04-25 at 11 06 21" src="https://cloud.githubusercontent.com/assets/1511715/25377228/4994f8f6-29a7-11e7-96d6-4ac4713aec99.png">

**Comment by abourdon** [comment]
Same behaviour from the Execution in queue page
