### ISSUE TITLE
library property name conflict? 

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1046]
This is a complicated behaviour to reproduce/give an example and does not happen all the time. Yet, it is annoying and happening for a long time (even in the oldest versions of Cerberus happened). I'll do my best to give the exact steps to reproduce: 
Let's say we have the testcase 0001C with the property CALCULATE_SOMETHING from the library LIBRARY_STEPS all working and with OK results. 

Then, I duplicate the testcase to 0001M with the same property CALCULATE_SOMETHING defined in the library LIBRARY_STEPS_MOBILE wich is slightly diferent and change the 0001M step to use it.

When running the 0001M testcase, it will use the CALCULATE_SOMETHING property from LIBRARY_STEPS instead of using the CALCULATE_SOMETHING from LIBRARY_STEPS_MOBILE.

I already lost lots of time wondering what is wrong with the testcase just to finnaly find out I have to rename or redefine the property in the testcase itself.

Does anyone else experienced this kind of issue? 

Thanks!

**Comment by pfoucray** [comment]
Hi,

Say you have several 2 steps in your 0001C Test Case, both of them are from the LIBRARY_STEPS.
Then 0001M, you change Step 2, for LIBRARY_STEPS_MOBILE, but Step 1 is still Linked to LIBRARY_STEPS.

Order of the steps is important : 
When Cerberus starts it's execution, it looks for all the properties coming from Test case itself, then properties coming from the libraries, starting orderly with library step 1, then library step 2.

If you have a different property with same name into 2 different Libraries, beeing used in the same TC, then...you either have to override the property in the test case or have to rename it in on of the libraries.

I asked as well if it was possible in that case, to make sure the property selected is the one USED in the step... but so far, it doesn't work that way, and isn't priority

@Cerberus dev : is it ?

**Comment by ruirpr** [comment]
different property with same name into 2 different libraries but used in different testcases, onde duplicated from the other.

**Comment by pfoucray** [comment]
What would be needed is : to import into a TestCase having UseSteps **ONLY** the inherited properties used in the Use-Steps. Not ALL properties of the Source Test-Case containing the Library.

**Comment by vertigo17** [comment]
Well there are no way to link the properties to import with the steps that are linked.
Properties are not linked to step but to the full testcase.
In case in a testcase, you use steps coming from different testcases, all corresponding properties will be imported.
I don't see any simple way to solve that appart from renaming the property with different names or (even better) avoid using mainsite steps inside mobile testcase to avoid conficts.
In other way, you should structure the step library with that constrain so that in case 2 testcase step library that have the same properties are not linked inside the same testcase.

I close the issue unless you propose a more simple solution.
