### ISSUE TITLE
Condition "never" is executed

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-source#1060]
Hi,

condition "never" is being executed.
Example bellow:

![1](https://cloud.githubusercontent.com/assets/14328346/21180208/d0db6464-c1ef-11e6-825f-1c1c8e2f32ad.png)

Test running:
![2](https://cloud.githubusercontent.com/assets/14328346/21180262/123fbf2c-c1f0-11e6-804c-424a4cf8759d.png)

Can you please take a look?

Thanks

**Comment by ffazendeiro** [comment]
Hi,
Seems that the condition ifPropertyExist does not work also.

Test case was created in to verify condition never:
http://cerberus.siege.red/Cerberus/TestCaseScript.jsp?test=Cerberus&testcase=9637A
Result:
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=40111760

Test case was created in to verify condition ifPropertyExist:
http://cerberus.siege.red/Cerberus/TestCaseScript.jsp?test=Cerberus&testcase=9638A
Result:
http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=40111852

Thanks.

**Comment by vertigo17** [comment]
This should be fixed with commit:
https://github.com/cerberustesting/cerberus-source/commit/2d00e4322fb0acc031c608349bc4c11c79d5f509
Can you test it with latest version ?
Conditional execution works at step, action and control level since that commit.
What is still missing thought is the same condition exection at the testcase level.
We can leave this issue open in order to solve that missing dev.
