### ISSUE TITLE
New release Cerberus1.1.10-SNAPSHOT-990 and Selenium 2.53.0 gives an error when run test cases

### ISSUE THREAD

**Issue by Anokasv** [cerberustesting/cerberus-source#1065]
Hello, 

After we update to the versions Cerberus1.1.10-SNAPSHOT-990 and Selenium 2.53.0, when we run the battery tests automatically gives the error "The test case is canceled due to lost connection to Selenium Server!". 
This affects a large number of tests.
If we run one at a time locally, the test passes successfully.

See example: http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=40162615

Can you take a look, please?
Thanks.
Ana

**Comment by bcivel** [comment]
I had a bit of investigation on your testcase and I saw that last execution give either OK, either KO before delivery page, or FA due to lost connection but always on the delivery page.

To help to investigate, regarding your other testcases, could you confirm all the FA due to this kind of error ("The test case is canceled due to lost connection to Selenium Server!") is limited to some pages or is it totally erratic?

Another test that you could do is to upgrade some of your robots to the same version than the Cerberus version (I mean Selenium 2.53) to see if it improve.

**Comment by bcivel** [comment]
linked #977

**Comment by bcivel** [comment]
fixed
