### ISSUE TITLE
Query wrt mobile automation

### ISSUE THREAD

**Issue by vikramvi** [cerberustesting/cerberus-source#1068]
Hi,
can you please clarify below

1. does it support native mobile app testing ( iOS & Android ) ?
2. does it support parallel run on android and iOS ?
3. does it have integration with Cucumber or any other BDD tool ?

Thanks,
Vikram

**Comment by vertigo17** [comment]
1. Yes through Appium connector for both Android and IOS (although IOS require Apple SDK on top)
2. Not sure what you mean on parallel run. Cerberus can of course executed hundreds of tests at the same time but I beleive the question is more if Appium support multiple execution in // on a single device ? Please confirm what you want to do ?
3. Cerberus has its own database to define the tests that are structure with action and controls that belong to steps that can be reused from 1 test to another easilly in order to keep maintenance of the test very low. Cerberus approch is different from cucumber as it provide a nice GUI in order to make the tests easy to read (not only to IT).

**Comment by bcivel** [comment]
Hi @vikramvi 
I guess you had answers to your questions, so I'm closing the issue.
Please, note that Cerberus is a layer above some automation tools like selenium, appium, sikuli...etc, that allow to centralize test cases, to manage cases efficiently though libraries, and that provide user interface for all kind of users being able to understand what is going to be tested.
Don't hesitate to reopen ticket if any point need to be clarified. 
I also take the opportunity of this ticket to thank you for the huge stuff you deliver especially for the appium community.
Thanks
Benoit

**Comment by vikramvi** [comment]
@bcivel  Thanks a ton for detailed clarification, sorry I missed to close the issue earlier.
I will try to use the framework in day to day work and get back in case of further queries.
