### ISSUE TITLE
[last version][critical] Step are executed twice 

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#1098]
Hi :)

Step are executed twice with last commit 

![image](https://cloud.githubusercontent.com/assets/995694/21682481/12773742-d355-11e6-8e71-a4e5c91560a2.png)

![image](https://cloud.githubusercontent.com/assets/995694/21682493/24826f6a-d355-11e6-8a28-09b6f85591e6.png)

It make the version unusable 

Thanks for your help

**Comment by vertigo17** [comment]
Fixed with last commit on #1007.
If you want to correct without the patch, the solution is to choose onceIfConditionTrue on Loop data for the corresponding steps (this is what the patch will do on Database Maintenance SQL)

![selection_166](https://cloud.githubusercontent.com/assets/5342048/21694814/53f2b200-d387-11e6-8f96-66269b314a12.jpg)
