### ISSUE TITLE
No detail in execution page

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1128]
Hello,
When a pre-step failed or is KO, there is no detail in execution page, only the xecution result is displayed : 
![prestepko](https://cloud.githubusercontent.com/assets/18569182/22102522/05231d3e-de38-11e6-97bd-15cb80d934cb.PNG)
Cerberus Version : 1.1.10-SNAPSHOT-1044
Thank you !

**Comment by ffsantos92** [comment]
**Temporary solution:**

You're still able to access to the "deprecated" version using the following url `http://domain/Cerberus/ExecutionDetail.jsp?id_tc=41417084`.

Just replace `41417084` by the `execution id`.

![capture](https://cloud.githubusercontent.com/assets/8303937/22104256/41cdcad8-de36-11e6-9989-ff9df7c6ed5b.PNG)

**Comment by abourdon** [comment]
It seems pre test case is not displayed on the execution page, whatever its return status.

**Comment by abourdon** [comment]
I reopen this issue because it is now not working again:

Pre-tests are correctly displayed when test is executing but no more when test is finished.

**Comment by mbessa** [comment]
Hello all,

This issue is still present in current version: Cerberus1.1.11-SNAPSHOT-1084. Isn't possible to see pre-test information in execution detail.
When analyzing some tests, specially the one's in which pre-tests open a specific URL (for instance VCCRM) it's very important to have this information available.

Thanks,
Marco
