### ISSUE TITLE
Possibility to run test cases by label

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#1156]
We manage our Releases/tests/developments  by features. 
In Cerberus, we translate it by association of a label to each feature.
A test case would have several label, or just one (it depends of the test...).

Is it possible to implement the ability to run all the test cases for one or several labels?
(in the interface or in command line, in order to run them throw jenkins for instance).

Thanks.

TODO List:
- [x] Add table to link campaign and label.
- [x] crud impact of new table
- [x] GUI impact (new tab to add list of label to campaign page)
- [x] Add list of testcase coming for label selection into AddToExecutionQueue Service
- [x] Add list of label inside RunTestCase Page

**Comment by vertigo17** [comment]
We will make labels managable at the same level as the battery level.
That means 
1/ allow to link a list of label to a campaign (campaign will then include all testcases that refers to those labels + batteries)
2/ allow to filter by label inside the run page.
That will take a bit of time.

**Comment by ping0uin** [comment]
Up.

we will manage the Cerberus intergration in our Feature Team, around the labels. 

The possibility for us to execute tests according to the label is very important to us.
Do you have news about this?

Thanks a lot.
Ping0uin

**Comment by vertigo17** [comment]
Hello @ping0uin, I start the dev on that ticket.
What is the most important ?
Adding label criteria in RunTestCase Page or add the possibility to add a list of label in AddToExecutionQueue service.

**Comment by ping0uin** [comment]
Hi @vertigo17 ,

so nice to read that. we just talk about this feature this morning.
The most important for now would be to add a list of label in AddToExecutionQueue Service. By this way, we will be able to launch tests cases by label with a HTTP request, like now.

Then, be able to filter the test cases in the RuneTestCase page is also interesting, but not a priority.

The main objective is well to launch automatically some tests cases in "command line"

Thanks for your question, and enjoy your dev ;)

**Comment by ping0uin** [comment]
I take an exemple. Here is a command to launch a campaign : 

http://10.9.72.68:18080/Cerberus/AddToExecutionQueue?SelectedCampaign=connexionTest&Environment=PROD&Browser=chrome&Robot=chrome_selenium_marc&ss_ip=10.16.187.118&ss_p=4444&Platform=LINUX&Tag=toto1&OutputFormat=compact&Verbose=0&Screenshot=1&PageSource=1&SeleniumLog=1&timeout=30000&retries=0

What it could be interesting is to remove the SelectedCampaign attribute and replace it by a list of labels like "TeamSiteWeb", "AjoutPanier", "CasNominal"...

**Comment by vertigo17** [comment]
Everything is possible ;-) But I propose you something else:
You still call with parameter SelectedCampaign=connexionTest and we change the GUI so that you can link the labels "TeamSiteWeb", "AjoutPanier", "CasNominal"... to it inside that screen.
![2017-04-13 18_21_44-testcampaign](https://cloud.githubusercontent.com/assets/5342048/25013959/1cb67ea2-2076-11e7-8aa6-db97702571e9.png)

That would be an additional tab similar to Battery but called label where you select the system and then the label to add in the list.

Another thing that I will have to ask Benoit is whether we need to feed the environnement parameter into that call. That could also be integrated to the campaign itself.
The idea behind the campaign is that it is self contain and once you have your CI tools configured the administration of the campaign is done directly inside Ceberus. No need to open the script once it works.

**Comment by vertigo17** [comment]
Anyway, I will put the prio on the CI integration vs manual execution using the runtest page.

**Comment by ping0uin** [comment]
Hi @vertigo17,

ok, thanks for your explanations.

I just have a question, in the UI, threw the campaign creation, the abillity to pick some labels will make dynamic campaign or not?
I mean, when a campaign is created on a label, if I add a new test case with the same label, may I have to modify the campaign also or it will be automatic?

Thanks in advance for your answer.
;)

**Comment by vertigo17** [comment]
Adding a testcase to a label that belong to the campaign will automatically include it when calling the campaign.
List of testcase will be retreived dynamically only when campaign is called.

**Comment by ping0uin** [comment]
Hi @vertigo17,

great to read it.
but I thought about something : what did you plan for the multiple labels in a same campaign?

For instance, you have a label "sanityCheck" and an other one "addInCart". Easy to create a campaign for all the tests case which are tagged with label "addInCart". But it will be possible to create a campaign only for the tests case for "addInCart" and "SanityCheck"?

I think it would be interesting to choose the operator between the labels for a campaign. &&, ||,...

what did you plan?

thanks in advance.

**Comment by vertigo17** [comment]
The initial plan is to make an union of all labels and battery in the scope of the campaign.
So operator will be "or"
Still, The result will be dedup.

Ex:
Label1 has tc1, tc2
Label2 has tc2, tc3

Campaign that include
Label1 and label2 will have Tc1 tc2 tc3
Label1 will have tc1, tc2
Label2 will have tc2, tc3

**Comment by ping0uin** [comment]
Ok. it is not the way we will use it. For us, it is basically a "and".

Ex:
tc1 has label1
tc2 has label1, label2
tc3 has label3
tc4 has label1, label3

campaign that include
Label1 will have tc1, tc2, tc4
label2 will have tc2
label1 and label3 will have tc1, tc2, tc3, tc4
...

do you think that it is possible to include in the label selection the operator ("and" or "OR")? 
The problem is that, if we need to modify the sources of cerberus after your release, we will not support next release anymore...

thx.

**Comment by vertigo17** [comment]
Maybe we have difficulties to understand each other but I can confirm that your example is what will be implemented.
The campaign that will have label1 and label3 will have all testcases in it.
Let me finish a first implementation and you will be able to confirm.

**Comment by ping0uin** [comment]
ok, no problem.

I just want to add  "shame on me".... in my exemple, the last sentence were wrong.

Ex:
tc1 has label1
tc2 has label1, label2
tc3 has label3
tc4 has label1, label3
tc5 has label1, label3, label4

campaign that include
Label1 will have tc1, tc2, tc4
label2 will have tc2
**label1 and label3 will have ONLY tc4**

But ok, I let you finish a first implementation, and let see how we could make it useful for us ;)

thx

**Comment by vertigo17** [comment]
That seems strange. If campaign include label1 (and optionally label2) feature why don't you expect tc1 to be executed inside that campaign ? I would because it has the feature.
I would expect that campaigns are create linked to a list of feature (linked to a piece of application).
On our case that would be something like we have a campaign to test the basket global feature and that campaign would include the features basket-promotion and basket-productrecomendation basket-header, etc.
When triggering the campaign, I would expect that any testcase that include at least 1 of those feature is in the scope of the campaign execution. Anyway there would probably have no test that covers all feature at the same time (and that would anyway be easier to handle testcase that cover as few feature as possible). 
We will probalby need to see each other in other to share on the subject as doing it in the ticket is tricky ;-).
