### ISSUE TITLE
Weird error when deleting a system

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1178]
Hello,
when deleting a SYSTEM, this error is displayed : 
![errorsystem](https://cloud.githubusercontent.com/assets/18569182/22509549/ce8e7532-e88e-11e6-82c5-9b65531b73b5.PNG)
Nothing is written. Could you please have a look ?
Thank you !

Cerberus Version : 1.1.11-SNAPSHOT-1050

**Comment by pfoucray** [comment]
FYI //

After Updating last Snapshot this morning, I confirm this issue is fixed,
**but** there is still a "missing doc !!!" over button suppression : 
![missing doc supp button invariants](https://cloud.githubusercontent.com/assets/16115517/22588090/a775c974-ea04-11e6-9bdd-64beff772ca2.png)

Regards,
PF

**Comment by bcivel** [comment]
Fixed. Thanks for having testing it ;-)
