### ISSUE TITLE
Cannot find xpath and action is not performed 

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1189]
Hi,
We notice that sometimes although the xpath is correct cerberus cannot find the path and return FA.
Execution example:
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=42128393
The filter size is available:
![image](https://cloud.githubusercontent.com/assets/17747042/22645779/aa630ec2-ec60-11e6-8d2e-ff0ab6c4dd45.png)
And the xpath **_//div[@data-cerberus='dropdown_plpProduit_sizeFilter']/dl_** is correct if we do it manually. It should click to expand the drop-down menu.
Version: Cerberus1.1.11-SNAPSHOT-1050
Thanks.

**Comment by bcivel** [comment]
Hi @ffazendeiro ,
By default, is it possible to define the getPageSource = onError when you execute testcases?
It will make us sure that the element that we try to find is present or not. 

Is it possible to provide one execution with that configuration?
Thanks

Benoit

**Comment by ffazendeiro** [comment]
Hi @bcivel,
Sorry for the late reply.
Not easy to replicate because the test hangs many times.
For example:
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=42143721
We had to stop it on the VM because it was running for 6013296ms.
But finally had and execution FA:
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=42145454
Like this it is very difficult to execute with success this simple test case.

**Comment by bcivel** [comment]
Dear @ffazendeiro 

I had a look to your example and as I suspected, the button you try to reach is inside a div that is display: none.

<img width="467" alt="capture d ecran 2017-02-07 a 21 27 28" src="https://cloud.githubusercontent.com/assets/5376184/22710103/663596c6-ed7c-11e6-85c4-89a08e69e269.png">

Maybe you can play with the condition on the visibility of this element to perform the click. 

For your problem of execution that never release, it appear that this problem happen in last versions of selenium. `Error communicating with the remote browser. It may have died.` . This issue is already reported there #950  so I close this issue.

As a temporar fix, on your robots, I advice you to set a process that kill the firefox process that is older than 5 minutes as described below
https://github.com/cerberustesting/cerberus-source/blob/master/tools/selenium/bin/kill-firefox-zombieprocess
At least, it will free the queue without any manual action from your side.
