### ISSUE TITLE
Need Info: Sample project using this framework for native mobile and parallel execution

### ISSUE THREAD

**Issue by vikramvi** [cerberustesting/cerberus-source#1196]
Hi,

Can you please clarify 

1. Any sample project to refer to understand usage of this framework

2. Does it support parallel execution with selenium grid ?

3. Any reason it's pointing to older version of appium java client instead of recent ?

Thanks & Regards,
Vikram

**Comment by bcivel** [comment]
Hi Vikram,

1. Sure, you can access here http://demo.cerberus-testing.org:8080/Cerberus/TestCaseScript.jsp?test=GUI%20%3A%20Transversal&testcase=0001A (user: cerberus ; password: cerberus). For the moment, I just set it, it's almost empty. I will feed some tests in the coming days and let you know.

2. It support parallel execution. Cerberus manage queuing and work with selenium grid (3 grids and 75 nodes) for testing on web application. For native (and hybrid) application, Cerberus call several appium servers (on several machine IP/Port) that manage 1 test at a time each.

3. We are using the java-client version 4.1.2, which is the last one before the 5.0.0-Beta. As soon as a version 5.0.0 will be delivered and approved, we will for sure upgrade.

Hope that clear enough. Don't hesitate to come back if not ;-)
Benoit

**Comment by vikramvi** [comment]
Hi @bcivel,

The link posted above is not working. Can you please fix it ?

Also please let me know support for latest version of Java Client if planned.

Thanks,
Vikram

**Comment by bcivel** [comment]
Hi @vikramvi 

The link above is no more working due to some migration on our side.
Please use this link instead :  http://demo.cerberus-testing.org/CerberusDEMO/TestCaseScript.jsp?test=GUI%20%3A%20Transversal&testcase=0001A
Beware, it's broken for the moment due to some maintenance task on our side.

Appium migration is currently in progress in Cerberus. This will be available during this week.

Ragards
Benoit

**Comment by vertigo17** [comment]
@vikramvi 
Even if this is subject to change, you can use this link:
http://demo.cerberus-testing.org:28080/CerberusDEMO/TestCaseList.jsp
User : cerberus
Password : cerberus
It will give you a list of sample tests that are configured. You can open one of them by clicking on 
![2017-10-30 17_52_53-test case list](https://user-images.githubusercontent.com/5342048/32184002-3488d22e-bd9b-11e7-8163-524a96e95f62.png)
in order to get the detail of actions performed inside the test.
Cerberus translate those actions defined from the GUI in Selenium/Appium/Sikuli actions depending on the application tested.
