### ISSUE TITLE
testcases hanging for no reason

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1214]
Once in a while testcases for ES and PT have a 'brain-freeze' and stop randomnly for no aparent reason. Every day, when we arrive, our vm's are filled with opened browsers for ES and PT and that is causing a major stress on testcase executions. 
![image](https://cloud.githubusercontent.com/assets/1914659/23503758/dfbecff2-ff34-11e6-8eb6-3f8f1914e8aa.png)

This situation only happens for PT and ES, no other country is affected. I have built some tests where this is perfectly clear:
![image](https://cloud.githubusercontent.com/assets/1914659/23503786/f6b6f298-ff34-11e6-972f-f6488e4ac155.png)

Sometimes the test hangs even in the calculateProperty action and the browser stays opened forever.

Since we can't find the problem, do you any ideia of what may be causing it? 

Issue in CS was also opened http://projects.cs-technologies.net/issues/34510

**Comment by bcivel** [comment]
Hello @ruirpr 
Unfortunatelly, not enough detail to reproduce :-)
Does it happen again on your side?
Did you check the network traffic to see if a request (from a third party tools for exemple) is pending?

**Comment by bcivel** [comment]
Hello @ruirpr 
Any news on it? Do you have more details?
Thanks
Benoit

**Comment by Anokasv** [comment]
Hello, 

Today, since 15:15 pm (FR Time), the Performance Test 5026D have the same behavior, 
http://192.168.134.17/Cerberus/ExecutionDetailList.jsp?test=Performance%20Monitor&testcase=5026D&country=PT&environment=PROD&systemFlt= 

All tests stay with PE status and in different steps. We can not understand why it is pending.

Can you please take a look?
Thanks.
Ana

**Comment by vertigo17** [comment]
Did you try to execute the test in a local VM ?

**Comment by Anokasv** [comment]
I executed the test in the VM's tests. It's not local.

**Comment by ruirpr** [comment]
Some more examples
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=46151281 running for 30 minutes
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=46151977 blocked on 'doing action'

both for ES

**Comment by mbessa** [comment]
Any update on this issue? This problem is causing PT and ES PROD Performance tests to congest performance HUB.
In less than 3 hours we have to restart the hub twice to clear queue. Tests from ES and PT fill all nodes instances and eventually stop running tests for other countries.
Please note we have more than 50 instances reserved for Performance tests, this should be more than enough.

**Comment by ruirpr** [comment]
Hi, 
did you had the time to investigate the hanged testcase executions?

**Comment by RobertoAbraul** [comment]
Hi,

this issue still present.
For PT and ES tests still hang without reason.
Examples:
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=46776194
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=46770192

Thanks.

**Comment by vertigo17** [comment]
I guess that comes from slow response time of the site.
