### ISSUE TITLE
loops and properties problem

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1246]
Hi, 
I'm facing the following issue. When using a property the loop allways use the value calculated in the first instance. When using the value directly in the action it works. 
For example, the following url: 
/ppdp/prod-%PRODUCT(%system.CURRENTSTEP_INDEX%)%.aspx
is being stored in the property URL_PRODUCT_L and this property is called inside a loop in the action openUrlWithBase. Property PRODUCT is defined as getFromDataLib with lenght 2 and already check both products are sucessufully retrieved. Cerberus open allways the same (1st) as you can see here:
http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=43904785 - to verify behaviour simply check the products opened
(also tested with . instead of () in http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=43905430 and does not work also)

But replacing the URL_PRODUCT_L in the openUrlWithBase action with the value /ppdp/prod-%PRODUCT(%system.CURRENTSTEP_INDEX%)%.aspx it works perfectly:
http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=43905627

So, i would like to use properties to make the test cleaner but right now is not possible. Is this working as expected and why is it working like this or is a real bug? 
Please, do not modify the test.

Thanks, 
Rui

**Comment by vertigo17** [comment]
Rui, this is the expected behaviour.

A/ I confirm that syntax with brakets () have exactly the same behaviour as dots .
I personally find dots more readable but both are maintained and supported.

B/ About property calculation.
The rule is that when a property is calculated, it is stored in memory during the execution.
The only 2 ways to calculate it is to: 1/ use it for the 1st time. 2/ force a calculate property action.
Please try to insert a calculateProperty action before the open URL and it should work.

Why don't you leave the version without the property. I personally find that we use too many property that make the test harder to read as needs to check the content of the property at every action.
In my view but it may be a matter of taste, I prefer to use property only on true testdata and not technical data such as concatenation of product id to build a url.
Please confirm the calculateProperty solve the issue and clode the ticket.
