### ISSUE TITLE
Not executed actions appear as pending

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1266]
Please check this execution on Step2 :
http://192.168.134.197/CerberusQA/ExecutionDetail2.jsp?executionId=44448910

Is this the expected, seemed more logic the previous behavior:
http://192.168.134.17/Cerberus/ExecutionDetail2.jsp?executionId=44719975

Thanks and Regards

**Comment by abourdon** [comment]
Hi @j0hnsa,

Again, please check your cerberus_url parameter value and try again.

Let us know,
Aurélien

**Comment by bcivel** [comment]
Hi @j0hnsa ,

Yes, the color of the row when action not executed is now blue (the same as PE). It is the new expected behavior.

The logic is that no action is needed for blue lines. In previous version, it was yellow (the same as FA) when fail mean something need to be done (in the test implementation or tested application).
