### ISSUE TITLE
empty testcase and error

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1268]
Hi, 
i was working on a testcase and now i get this:
![image](https://cloud.githubusercontent.com/assets/1914659/24873399/91a37518-1e18-11e7-81e9-9431a695b9a4.png)

Do you know what may be happening? Did i lost the work? i really hope not...

**Comment by ruirpr** [comment]
Just checked and steps are still in bd.

**Comment by ruirpr** [comment]
Any ideia on how i can get the testcase to show?

**Comment by abourdon** [comment]
Your test case is using an unknown #16 step from the given test case: http://cerberus.siege.red/Cerberus/TestCaseScript.jsp?test=THESEUS_StepLibrary&testcase=0020A&step=16
Actually, there are only 15 steps in this test case

Curious, because deleting a step cannot be done if already used.

Do you know what's happened?

**Comment by ruirpr** [comment]
Thanks, that helped to solve the problem. It seems that the last step from the library was deleted. Probably related to the problem that if the user hit save before the page is fully loaded, cerberus saves only the steps on the page. Could somthing to prevent this be implemented?

**Comment by abourdon** [comment]
Ok so related with #1167  and #1168
