### ISSUE TITLE
IfProperty exists - behavior suggestion

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1280]
Hello,

Considering the scenario that a property is not calculated because it didnt met the condition we have on a test would it be possible on a following action to use ifPropertyExists skip this action because this property wasn't calculated?

See this example:
http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=44975119

On step 5 property isn't calculated following the condition

On step 6 It considers that the property exists and it fails.

Cerberus Version : 1.1.12-SNAPSHOT-1128

**Comment by j0hnsa** [comment]
Its working with the following settings On step 6 we use the condition IfStringDifferent %GET_SIZE_FILTER_QTY% and '' on the condition2 value, although I think its more complicated to understand:

http://cerberus.siege.red/Cerberus/ExecutionDetail2.jsp?executionId=44976938

Thanks and Regards

**Comment by vertigo17** [comment]
I confirm that ifPropertyExist only checks if the property has been defined on the testcase (or inherited) for the corresponding country. It does not check the value (and do not try to calculate it if not already calculated).
So this is normal that on your 1st execution the control execute and fail. In fact it fail when decode the value2 of the control.

On your second execution, it still tries to calculate the property %GET_SIZE_FILTER_QTY% but when doing the condition. And it fail doing it because element do not exist. It failed still on a decode property but inside condition value2.

The thing that I need to correct is that the FA control should generate a FA execution on both cases. I will have a look to it.
The expected result in both cases is to generate a FA. I beleive this is not what you wanted to acheive.

Can you clarify what you really wanted to do ?

**Comment by j0hnsa** [comment]
The purpose is achieved on the second case as I'm getting OK on overall execution, although is not really user-friendly and can lead to doubts if the user is looking to the execution for the first time.
I wouldn't reach this solution honestly but it was suggested by Filipe and made the trick. In my modest opinion my suggestion would be simpler to understand. When a property is not calculated following some condition it should be considered as it wouldn't exist.

Although I understand that FA should be generated on the second case because it fails to get a certain element I wouldn't know how to work around this type of case, so maybe can be useful to leave it like this.

**Comment by vertigo17** [comment]
Sorry but I will have to fix this and we will have to find another solution.
I cannot leave a FA control generating an OK execution.
