### ISSUE TITLE
Test case with an upload

### ISSUE THREAD

**Issue by MamounElAlaoui** [cerberustesting/cerberus-source#1303]
When testing a form with a file upload, there is no way to tests the upload on cerberus but it is possible on selenium.
I tried with a click on the input and a manageDialog OK but it didn't work.

**Comment by R-Loic** [comment]
Hello @MamounElAlaoui ,
In fact, you have to use the action KEYPRESS and "ENTER" but it is not working for the moment, This error message is displayed:  
"Environment configurations don't allow you to perform the KeyPress operation."
@bcivel will check as soon as possible.

**Comment by bcivel** [comment]
Hello @MamounElAlaoui, @R-Loic,

Unfortunatelly, the implementation proposed using 
`[action=keypress, value1=<empty> and value2=ENTER]` 
doesn't work on non-linux environment. I'll have further investigation but I feel it won't be possible to do without running some deamon on robot machine.

As a workaround, I would advice to use :
`[action=type, value1=web_element_type_file, value2=/the/path/to/the/file/to/upload.txt]` 
instead of the actions that click on the button, choose the file and click on validate.

Thanks for the feedback

**Comment by nicodeur** [comment]
Hello,

We will add this best prctice on online documention, and close the ticket after.

**Comment by vertigo17** [comment]
Sikuli extention should be used for that case.

**Comment by InkUisitor** [comment]
Hello,
I faced the same issue with an upload on an invisible input with a file type. I'm used to Selenium which use the command sendKeys to upload a file on a WebElement. But here again, Selenium needs a visible input file type to perform the upload.
In order to success the upload (specially when the input is invisible), you will need to declare these 3 actions in your step :

- **Action "Execute Javascript"** : document.getElementById("myInputFileInvisible").style = "display : block;";
With this action, your input will be visible

- **Action type (function 5.3.26 of the documentation)**
_Type a data in an Element._
_Value1 : Identifier and name of the element where the data is entered in the form of : identifier=html_reference._
For this example : id = myInputFileInvisible
_Value2 : data to enter in the field._
Write the complete path of your file (with absolute path) :
For a node running on Unix : /home/seluser/Downloads/mySample.pdf
For a node running on Windows : C:/Data/CerberusFiles/mySample.pdf

- **Action "Execute Javascript"** again but this time in order to hide your input again
document.getElementById("myInputFileInvisible").style = "display : none;";

It's a bit weird, but if your need to upload a few files in your campaign this will be enough. I will try to propose a solution directly for Cerberus based on this with a new function if I have enough time.

**Comment by Kevin-Sinapayen** [comment]
Hello,
Thank you for these answers, very helpful.
I have a question about where to find the PDF files. I'm currently using the free SaaS version of Cerberus for a POC, so I don't have any access to the filesystem.
How can I use these samples?

For a node running on Unix : /home/seluser/Downloads/mySample.pdf
For a node running on Windows : C:/Data/CerberusFiles/mySample.pdf

Or is there another way?
Thanks for your help.
