### ISSUE TITLE
JavaNullPointer when calculating datalib SQL

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1310]
Hello,

There is the following error which happens at every execution : 
![image](https://cloud.githubusercontent.com/assets/18569182/26406470/a7ee3e3c-4098-11e7-80aa-b2c7c853d5e3.png)

TR7202A is property GetFromDatalib which is a SQL.
Thank you

Cerberus Version : 1.1.13-SNAPSHOT-1150

**Comment by abourdon** [comment]
A the line of this error, (ActionService:1110), stack trace has not been added to application log, so we cannot see the cause of this NPE. I added this information to the commit ed59f4c6591d0aaf4d710bbfff24536f14429763. Could you test again and tell us?

Regards

**Comment by gmoita** [comment]
Hi.
Problem persists for datalib VOL_TR7202 entry.
Here is the log of the error:
[#|2017-05-24T17:15:48.275+0200|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=150;_ThreadName=Thread-2;|2017-05-24 17:15:48 INFO  SQLService:465 - Sending to external Database (queryDatabaseNColumns) : 'AS400_UAT_FR' SQL 'SELECT t2.*, TRIM(t2.MOTDISPO) AS MOTDISPO1, TRIM(t2.CSWHCOD) AS CSWHCOD1 FROM TR7202 t2
WHERE t2.CODSOC = '1'
AND t2.NUMCDE = 163746730803
FETCH FIRST 20 ROWS ONLY'
|#]

[#|2017-05-24T17:15:48.306+0200|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=150;_ThreadName=Thread-2;|2017-05-24 17:15:48 INFO  RecorderService:492 - Starting to save File - recordFile.
|#]

[#|2017-05-24T17:15:48.310+0200|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=150;_ThreadName=Thread-2;|2017-05-24 17:15:48 ERROR ActionService:1110 - java.lang.NullPointerException
java.lang.NullPointerException
|#]
Execution is http://cerberus.siege.red/CerberusRegression/ExecutionDetail2.jsp?executionId=46730803

**Comment by abourdon** [comment]
@gmoita we know, previous commit was just to add stack trace information.

Now, stack trace is the following:
<img width="1540" alt="screen shot 2017-05-24 at 17 22 00" src="https://cloud.githubusercontent.com/assets/1511715/26411254/c0166180-40a5-11e7-899a-e230e77890bb.png">

By reading the code at org.cerberus.engine.gwt.impl.ActionService.doActionCalculateProperty(ActionService.java:1075), we see: 
<img width="1038" alt="screen shot 2017-05-24 at 17 24 55" src="https://cloud.githubusercontent.com/assets/1511715/26411337/f1ea22b4-40a5-11e7-8126-730037c77c85.png">

Thus, `value1` or `tcExeData.getValue()` seems to be null. @R-Loic says that `value1` is well defined so we have to investigate how is computed the `tcExeData.getValue()` value

Maybe @vertigo17 could help because he recently worked on it.

**Comment by gmoita** [comment]
Sorry, I didn't knew that.
Additional info, from the logs, before the error happens.
[#|2017-05-24T17:15:47.859+0200|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=150;_ThreadName=Thread-2;|2017-05-24 17:15:47 INFO  DatabaseSpring:40 - connecting to jdbc/AS400_UAT_FR
|#]

[#|2017-05-24T17:15:47.878+0200|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=150;_ThreadName=Thread-2;|2017-05-24 17:15:47 INFO  SQLService:209 - Sending to external Database (queryDatabase) : 'AS400_UAT_FR' SQL 'SELECT NUMCDE
FROM tr7202
WHERE CODSOC = '1'
AND NUMCDE = 163746730803
FETCH FIRST 20 ROWS ONLY'
|#]

[#|2017-05-24T17:15:47.910+0200|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=150;_ThreadName=Thread-2;|2017-05-24 17:15:47 ERROR ParameterService:100 - Error when trying to retreive parameter : 'cerberus_externalsql_timeout' for system : 'vol-ord'. Default value returned : '60'. Trace : org.cerberus.exception.CerberusException
|#]

Can this have any impact on the result?

**Comment by abourdon** [comment]
I don't think so but thank you for the investigation

**Comment by abourdon** [comment]
@gmoita could you please turn on debug logs on QA?
