### ISSUE TITLE
properties calculation

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1341]
Hello,

On action "calculate property" I have to "force execution : PE". If not, the Test Case will stop and have a FAIL status. (for every properties : "JS", "dataLib", "text",...).
Otherwise, executing Test Case : when a property is called, it will always have the same value, even using the "calculate property" action. 
As basic exemple, I want the property "NUMBER_OF_ARTICLES" to store the number of articles displayed in the basket logo. This is OK, but I can't "refresh" the stored value : once calculated, "NUMBER_OF_ARTICLES" will just return the same value.
Are those two issues related? 

Thanks,

**Comment by vertigo17** [comment]
Unfortunately not documented but the rule is:
When you use a property putting %property.zzzz% anywhere in fields that are decoded (mainly actions, control, or property value1 and value2), Property is calculated only if it was never calculated. In case it was already calculated the same value is reused.
If you want to force its calculation, you need to specificaly add the action calculateProperty with value1=zzzz that will recalculate the property with the new value. (of course you need to check that the context is available at the time of the calculateProperty action - means that in case you access by js to a html field, the field needs to be visible on the current page when action is triggered).

On your example, if the basket logo is available at the time the action calculateProperty is called, it should refresh the value of NUMBER_OF_ARTICLES with the new calculated value.

If you get a failed action that is due to a real error when trying to calculate the property.
What is the FA error that is returned ?
If not confidencial, please provide the result of /ReadTestCaseExecution?executionId=12345
That report a json format of the execution result.

**Comment by vertigo17** [comment]
I close it and let you reopen with more detail if you still have the issue.
