### ISSUE TITLE
put LABELS not removable and non-editable

### ISSUE THREAD

**Issue by simondz** [cerberustesting/cerberus-source#1343]
In order to protect the use of LABELS, is it possible to make impossible the delete of LABEL as long as they are associated with a test case?
And protect LABELS so that they can only be edited by admin profiles?

Perhaps by going through the configuration (Administration>Parameters) to make it possible to adapt this need to each use?

**Comment by vertigo17** [comment]
Can I propose that we create a label group that can be administered at user level in order to give or not the right to create, modify and update labels.
If we do that, is that really necessary to check that labels are used before editing them ?
I will automatically put all users in test group in that new group so that deploy will be transparent with the additional feature to remove the access to labels.
That way the parameter to me is not necessary.

**Comment by simondz** [comment]
Thanks @vertigo17 

That seems to me to be a good answer to the question. For us, the main thing is to avoid label deletions because they are essential in our management of test executions.
