### ISSUE TITLE
Execution queue mass actions no longuer works.

### ISSUE THREAD

**Issue by vertigo17** [cerberustesting/cerberus-source#1352]
To reproduce:
Open /ExecutionPending.jsp page (Menu Run / Executions in Queue).
Select the 1st execution in the list (create 1 if no execution in the list).
Click Mass Action
Choose Delete TAB and click DELETE button.

Waiting layer appear forever.

![image](https://user-images.githubusercontent.com/5342048/27507100-8faac8e8-58c8-11e7-9816-053b99103e42.png)

View from Debug mode that report a 400 return code.

![image](https://user-images.githubusercontent.com/5342048/27507110-c66cf248-58c8-11e7-8dca-819706a738cc.png)

I did not test all mass actions but I guess none of them work.

**Comment by abourdon** [comment]
Fixed but strange: bug was due to an incompatible type between payload encoding and content-type declaration (json vs form) because of a bad use of the JQuery's post method. But this code was not been updated since February while users are using the ExecutionPeding page every day...

Anyway, it's fixed now.

Aurélien
