### ISSUE TITLE
Automatic redirection to sikuli node ?

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1381]
Hello,

With a selenium architecture using a sikuli node, would it be possible to execute sikuli tests by using the selenium hub ? The hub would redirect to the sikuli node automatically. Currently, it's not the case, we have to set the robot for calling the node.

Thank you

**Comment by bcivel** [comment]
Hello @R-Loic 
Unfortunately, not possible to do that way because selenium does not allow to do it.
But since my last commit, you can now start the cerberus-extension-sikuli in a standalone mode, without selenium.
That should simplify your installation if you're testing fat client. You just have to start your server using : 
`java -jar cerberus-extension-sikuli-1.1.0-full.jar`
