### ISSUE TITLE
ReportingExecutionByTag and ByDate

### ISSUE THREAD

**Issue by simondz** [cerberustesting/cerberus-source#1382]
How can I retrieve tag executions on dashboard for a given period?

For exemple, with an URL like : 
ReportingExecutionByTag.jsp?Tag=XXXXXXX&DateStart=20170712-1100&DateEnd=20170713-1745

This looks like #806

**Comment by vertigo17** [comment]
Sorry @simondz but we will not implement that feature.
Tag should be limited in time (based on a period of testing within a single release process).
Since few commits ago, there are no restriction to create as many tag as necessary.

Adding the filter by tag will encourage the users to keep the same tag id forever which is not the way to do for performance reasons.

I will reopen the #806 issue though in order to filter homepage by tag (as now tag is also lined with campaign).
