### ISSUE TITLE
Execution Detail in TestCaseExecution don't display correctly

### ISSUE THREAD

**Issue by Ronpiche** [cerberustesting/cerberus-source#1386]

**Comment by vertigo17** [comment]
In order to detail a bit the issue:

- [ ] Most of the fields on the execution detail screen are not loaded (empty). Ex Start, End, ...
- [ ] The execution status is recalculated when page loaded and not taken from database. That cause FA Execution to be displayed as KO.
- [ ] Any rule that use the status = PE should be replaced by ManualExe = true. (ex : display of manual buttons)
