### ISSUE TITLE
Can't select another step if we insert a new step

### ISSUE THREAD

**Issue by Anokasv** [cerberustesting/cerberus-source#1417]
Hello, 

When we add a new step, we can´t acess to another step. This not happen if we save the test case first.
Scenario:
1 - Click on button "Add step" and select one;
2 - Click on a step that already exist (see atachment).

You think it's possible to change this behavior?
Thanks.
Ana

Cerberus Version: 1.1.14-SNAPSHOT-1185

![step](https://user-images.githubusercontent.com/20952253/28829226-f51c6d1a-76ca-11e7-8560-9b749f80565e.png)

**Comment by Anokasv** [comment]
Hello, 

Just to inform that we have anothers problems:

Scenario 1: if we click on "add step" and close, and select one of the steps, the selection is on the two steps (see atachment) 

Scenario 2: if we click on "add step" and search for a step and close, the behavior is the same that I describe on the issue.
![step1](https://user-images.githubusercontent.com/20952253/28830021-80891efa-76cd-11e7-80d5-52bb2ebe13d0.png)

**Comment by bcivel** [comment]
Hello @Anokasv 
I cannot reproduce none of your issues. Could you please tell me what is your browser / version for me to check that way?
Does it happen on another browser?
Thanks

**Comment by Anokasv** [comment]
Hello, 

We tested this situation on two browsers:
 - Firefox ESR 52.2.1
 - Google Chrome Versão 59.0.3071.115

If you need more information, please contact us.
Thanks
Ana

**Comment by bcivel** [comment]
@Anokasv 
Could you please have a look to your browser console (F12), to tell me if you get any error?
Thanks

**Comment by ffazendeiro** [comment]
Hi,
This issue seem to be present only if we use the search when adding a step to the test case.
1. If we add a new step all is OK
2. If we choose a existing step to scrolling through the list all is OK
3. If we use the search to locate a step the issue is then present (no need to add the step to the test, if we just close the "Add Step" window the issue is present). See image below:
![image](https://user-images.githubusercontent.com/17747042/28835230-94a29f92-76dc-11e7-92ee-2a8ece262085.png)

Using the browser console no new error is reported when opening "Add Step" option or using the search.
We only have some error loading the test case page (/TestCaseScript.jsp?):
![image](https://user-images.githubusercontent.com/17747042/28835370-031d5c96-76dd-11e7-890c-86b82512f29e.png)

Tests done on Google Chrome 59.0.3071.115

Thanks.

**Comment by bcivel** [comment]
Thanks for the help. 
That should be solved with my last commit.
Thanks
Benoit
