### ISSUE TITLE
What's the "Database URL" purpose for CSV DataLib ?

### ISSUE THREAD

**Issue by TsunaDev** [cerberustesting/cerberus-source#1440]
![image](https://user-images.githubusercontent.com/30118815/29070752-e86f70b4-7c40-11e7-8fe0-887f08c03413.png)

**Comment by vertigo17** [comment]
It is used to have different locations for csv files depending on environment. That allow 1 datalib definition that will load different data depending on the env where the test runs.
It is the same use as the database for sql configuration.
You need to feed the csv url in env screen of th corresponding database to make it work.
I enriched documentation with my last comit https://github.com/cerberustesting/cerberus-source/commit/8b820b3f2210b6cc4c3c9561fc70e3770cfa4a2c in order to try to make it more clear.
Please reopen if still not clear and I will enrich doc even more.

**Comment by TsunaDev** [comment]
@vertigo17 , thanks for the answer !

I have an error I don't really understand : 
![image](https://user-images.githubusercontent.com/30118815/29159902-85806942-7db0-11e7-822b-52c055360e00.png)

Does that mean that I have to create a column for each data in the CSV file ?

**Comment by vertigo17** [comment]
No it means that on the definition of your datalib "products" you need to define at least 1 subdata with the column position. All your datalib subdata are empty.
For every subdata you want to access you need to give the column position (map the name of the subdata with an integer value that define the position in the file).
I will try to provide a screenshot later today.

**Comment by vertigo17** [comment]
I enriched the documentation with examples on how to feed subdata for CSV datalib.
