### ISSUE TITLE
Identifer should be proposed with a drop down menu

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1441]
Hello,

It would be great if the identifier for all actions could be proposed with a drop down menu : 
![image](https://user-images.githubusercontent.com/18569182/29122448-b1039f60-7d12-11e7-91e4-a71c44e1735e.png)
It will appear when the action need an identifier with the identifier list available for this specific action.
It will be more user friendly.

Thanks !
Cerberus Version : 1.1.14-SNAPSHOT-1202

**Comment by vertigo17** [comment]
Why not making an autocomplete ?
Adding a new field will make other field even smaller.

**Comment by cDelage** [comment]
Hello

I thinks it's because the selector field can take different values. I'm not
expert on the question so i'll speak about it with ryltar and i going back
to you.


Le ven. 24 août 2018 à 07:53, Benoit DUMONT <notifications@github.com> a
écrit :

**Comment by vertigo17** [comment]
Enriching existing autocomplete feature by proposing the identifier only when field is empty or at the beginning of the field could have been easier to implement and i think easier to use. 
We could have take the oportunity also to refactor that autocomplete feature by moving all js code of autocomplete to a different js file in order to make it available in other pages where decode is also possible (datalib or service or robot)

Yes share that with ryltar and we can discuss that next week when i will be back. 

BTW i saw 2 issue on current implem : 
-new field is not disabled when it should be (read only or use step) 
- in case there is 2 = inside the field everything after the second = disappear from the GUI and potentially get lost when saving.

**Comment by cDelage** [comment]
Hi Benoit,

If i testing my new method in test like you speak about yesterday, and it's
okay, can i work on the Front interface in local this weekend and show my
work monday or last before push?

Have a nice weekend,

Corentin.

Le ven. 31 août 2018 à 09:51, Guillaume Martin <notifications@github.com> a
écrit :

**Comment by vertigo17** [comment]
Sure. Have a nice WE too.
