### ISSUE TITLE
Automatic queue retry

### ISSUE THREAD

**Issue by Heychsea** [cerberustesting/cerberus-source#1462]
In my campaigns there are always some tests which aren't launched because of a connection reset.
The thing is I don't want to restart them myself (because of automation), and the retry parameter doesn't seem to affect it. Is it possible to make an automatic queue retry or something like that ?

**Comment by vertigo17** [comment]
You need to provide more detail. 
How did you submit the executions ?
What are the status of those executions in queue (QUEUED, DONE, ERROR) ?
Did execution triggered ? What was the exe status at the end ? (FA, KO)

In case execution was submitted, retry will automatically triggered a new exe to queued if end status is not = OK.
From what i understand it should be enought for your need.

**Comment by Heychsea** [comment]
The executions are usually done by the servlet command, and end in "ERROR" status (displayed as "QU" in the campaign). I think the tests does not restart because they didn't even launch.

**Comment by vertigo17** [comment]
This is correct, retry only works if execution was triggered.
Here the test did not start link with preliminary controls.
What is the ERROR State message in the queue ? If it is a Selenium connection reset, I guess it happened because the selenium server is over loaded and cannot support the parallel execution.
Did you try to limit the parallel execution by tuning robothost invariant on your selenium server IP ? Another option is to setup a selenium hub that could support a lot more executions in parallel.

**Comment by Heychsea** [comment]
The tests were without selenium (SQL tests) and the connection reset was solved by lessening the size of the execution pool.

**Comment by vertigo17** [comment]
I suppose you decrease the pool size at application/environment level.
Anyway, I believe we can close the issue.
You can reopen it if needed.
