### ISSUE TITLE
new tag not displayed on execution reporting by tag filter

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1470]
Hi,
On the execution report by tag page it seems that not all the tags are loaded or present when filtering.
For example:
![image](https://user-images.githubusercontent.com/17747042/30203575-5342af86-947a-11e7-97f1-db72223ca26a.png)
The tag **WHSALE_Non_Regression_A_UAT_2017090807** exist and there were tests executed (47) but when we filter by **20170908** no tag are showed.
If we enter the complete URL (ReportingExecutionByTag.jsp?Tag=WHSALE_Non_Regression_A_UAT_2017090807) and submit it we go to the correct report page. If we submit the same URL another time then the tag is present on the search (it seems that doing this the tag was added to the list) but not the others.
In the next example we can see tag **WHSALE_Non_Regression_A1_UAT_2017090807** was executed but now filtering again with **20170908** the previous tag is now present but it is the only one:
![image](https://user-images.githubusercontent.com/17747042/30203843-61e9db08-947b-11e7-8045-fcdabe97438a.png)

Thanks.

**Comment by vertigo17** [comment]
@ffazendeiro this is strange indeed as right now I cannot reproduce.
But can confirm the problem exist as all the 47 executions were created around 2017-09-08 07:15:33.0
The Tag was created at 2017-09-08 10:47:18.0 by it130238.
Can you confirm who is it130238 and what action on what screen he did at 10:47:18.0 in order to create the tag. I bet a single execution on which he got an error with no execution but I would like confirmation.
I also need (even more important) the actions that was done at 2017-09-08 07:15:33.0 that created the 47 execution. There must be something wrong that prevent the tag to create at that time.

**Comment by ffazendeiro** [comment]
Hi @vertigo17,
1.) it130238 is my login credentials in Cerberus.
2.) the tag were generated by a scheduled task (at 07:15) using the "old" servlet version (it was not yet updated to the new one). Example of an automatic execution: 
http://192.168.134.17/Cerberus/RunTestCase?ss_ip=192.168.135.101&ss_p=5555&browser=firefox&Test=WHOLESALE NON REGRESSION&TestCase=0025A_RU&Country=RX&Environment=UAT&Tag=WHSALE_Non_Regression_A1_UAT_2017090807&verbose=0&outputformat=compact&screenshot=1&pageSource=1&seleniumLog=1
3.) At 10:47one of the test was re-executed with the tag. Opened test case execution (TestCaseExecution.jsp) from the Reporting Execution by tag page and selected "Run this test case again"

Thanks in advance.
