### ISSUE TITLE
Add Robot to a test

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1478]
Hello,

Would it be possible to add selection of a robot to a test on Robot contraints tab when editing the test?

![imagem](https://user-images.githubusercontent.com/16339891/30327585-82789c5a-97c4-11e7-96a4-bf665cd71fe1.png)

Cerberus Version : 1.1.14-SNAPSHOT-1219

**Comment by bcivel** [comment]
Hello @j0hnsa 
It brings a lot of complexity and rules doing that. Could you detail what you need exactly please?
I guess some capability as the device type of orientation.

Thanks
Benoit

**Comment by j0hnsa** [comment]
Hello @bcivel ,

It would allow me to have just one campaign of mobile apps and maybe in future to use Queue just like we are doing on mainsite. Just the device id wouldn't be enough unfortunately...

Anyway you can close this request if its not so easy...

Regards

**Comment by j0hnsa** [comment]
Hi @vertigo17 ,

I would like to do so but there are still some problems with that, current situation:
- 3 devices (iphone, tablet and smartphone)
- 3 running instances of appium (ex Port:5556 for iOS Port:5557 smartphone Port:5558 tablet)
- 6 campaigns, one for each device and version we are testing (current and previous)
- 5 robots (1 for ios and 2 for each android device because I need to specify the launch activity for each version of the app which is not the same) specifying the Port and Device id and Automation name and launch activity
- 4 applications (ANDROID ANDROID_NEW IOS IOS_NEW)

Launching AddToExecutionQueueV001 doesn't work as we are testing 3 Countries  with Poolsize to 1 each but we only have one device and it would try to launch 3 tests at the same time. I guess this can be solved in other ways rather than adding a robot constraint to a test. But at the moment I can't take profit of AddToExecutionQueueV001 or is there an argument to specify the number of workers on each call (Poolsize applied to Application)?

Can you please advise how should I proceed then?

Regards

**Comment by vertigo17** [comment]
I better understand ;-)
I have a proposal :
Can you put the 3 appium on 3 different IP and define a poolsize at 1 for each robot IP. If I understood well that would secure to have 1 execution at a time on each device

If that works we could implement a new constrain per robot ip + port in order to put back all appium on 1 single url. 

The target we should aim is to be able to trigger all executions at the same time and define the constrain in order to secure it works well.

**Comment by j0hnsa** [comment]
Where can I define the poolsize to a robot? On appium side we dont have that constraint (unless we use selenium grid maybe)

Regards

**Comment by j0hnsa** [comment]
I successfuly launched a campaign using AddToExecutionQueueV001 and using selenium grid. I still have the same problem, separated campaings for devices and version of the app but it works! Later on I'll make some tests to see if we can profit of a faster execution time.

Thanks

**Comment by vertigo17** [comment]
chapter 7.4 of documentation will explain how to configure the robot host constrain. I checked and full detail is there with screenshots ;-).

I don't see the problem of keeping different campaign for devices and version of the app. 
Does that means that you triggered all your campaign (6) with multiple calls to servlet (at least 6) with the correct robot attached to each calls ? You already configured a pool constrains of 1 to the target appium server ?
If you done that I guess the issue is now that you have now only 1 execution at a time when in fact there could be 3 (1 for each appium/device).

I have a proposal to fix that easily:
Let's try to put in the host of the robot :
Port5556@host
Port5557@host
Port5558@host
Adding PortXXXX@ in the beginning of the host will allow you to have different entries from Cerberus point of view (allowing to put a constrain of 1 on each) and PortXXXX@ should be ignored from Appium as it does not care of authorisation.

Can you test that ?

**Comment by j0hnsa** [comment]
I was able to do so using selenium grid otherwise if i make those 6 calls Cerberus won't know if the device is available or not and all the calls get mixed up, appiumserver don't have the ability to limit the connections to 1 besides using the GRID.

I'll perform some tests and come back to this topic to discuss if any change is needed on Cerberus to make it work.

Thanks

**Comment by j0hnsa** [comment]
I've checked the Documentation and I'll give that a try as well!

Thanks

**Comment by vertigo17** [comment]
If Selenium mix the calls, keep the Appium isolated on each device and separate the host with the trick on Portnnn@IP in order to define a constrain per IP+Port (Appium constrain).
That should work.

**Comment by j0hnsa** [comment]
Hi @vertigo17 ,

It works with the trick:
Port5556@host
Port5557@host
Port5558@host

Thanks for the help!
