### ISSUE TITLE
Failed results when executing a testcase on several resolutions

### ISSUE THREAD

**Issue by minigrou** [cerberustesting/cerberus-source#1479]
Hi,

While executing our testcases (both for Web and Heavy client), we are facing with following issue:

- Testcase implementation is actually being done on a laptop in 1366*768 resolution;

- Result of this testcase may be 'Ok' on this resolution;

- As soon as this testcase is executed on a screen with another resolution (dual screen, screen in a meeting room...), its execution fails because the robots, whereas it is Sikuli or Selenium, do not find some items anymore.

Those items (buttons, fields, ...) actually appear on a 'small' screen, but not anymore on a bigger screen where one or several scroll(s) may be required to make them appear. And those steps are not necessarily implemented in testcases at the beginning, because they are not required on the resolution on which the testcase was implemented. Therefore testcase execution fails.

Our remarks and questions regarding that:

1/ We can't record the screen on which the testcase execution works correctly to broadcast the result, because a complete and live execution of the testcase may be required at any time during meetings;

2/ How can we make a testcase executed correctly, and without any error, in any resolution?

Kind regards,
Élodie Débureaux

**Comment by vertigo17** [comment]
That looks like a Selenium and Sikuli constrain but looks to me that it is not a bug.
Sikuli and Selenium cannot interact with an element that is not display (just like a normal user) so that should generate a FA return code.
You need to specify the test on smallest resolution in order to reduce that risk.

Not sure I understand your 1/ remark. What do you mean by 'record the screen', 'broadcast the result' & 'meetings' ?

**Comment by edebureaux** [comment]
Hi.

Ok, thanks for your answer.

Sorry for the misunderstanding about my 1/ remark.

I meant that one solution to avoid the issue would be to record the testcase execution on the screen on which the testcase was initially implemented, so that we are sure that we can broadcast this recording with other people (for example, during a meeting) and therefore are able to display a correct execution.

But unfortunately, I am not enabled to do that because those people want the tool to be working during the meeting, and do not want to see a video on which the tool has worked previously.

Is it clearer for you?

________________________________
De : Benoit DUMONT <notifications@github.com>
Envoyé : jeudi 21 septembre 2017 21:23:04
À : cerberustesting/cerberus-source
Cc : Élodie Débureaux; Author
Objet : Re: [cerberustesting/cerberus-source] Failed results when executing a testcase on several resolutions (#1479)


That looks like a Selenium and Sikuli constrain but looks to me that it is not a bug.
Sikuli and Selenium cannot interact with an element that is not display (just like a normal user) so that should generate a FA return code.
You need to specify the test on smallest resolution in order to reduce that risk.

Not sure I understand your 1/ remark. What do you mean by 'record the screen', 'broadcast the result' & 'meetings' ?

**Comment by vertigo17** [comment]
If you configure your desktop in single screen (to avoid wierd behaviour on dual screen config) and test a responsive application, there are no reason why it should not work.
Now if your application is not responsive and you try to access an element that is not visible on a certain resolution, it is good to see that Cerberus FA doing that. It is the purpose of the test to validate that it works (or not) on a given resolution.
Please share with @R-Loic what is the best or detail the test that works on a certain resolution that is not working on another (when it should).
