### ISSUE TITLE
[SUGGESTION] - When retrying a test fill the robot setting with the same robot used prev

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1515]
Hello,

When a test fails and we click ->
![2017-10-19 12_28_59-execution detail](https://user-images.githubusercontent.com/16339891/31768927-4cc86a6e-b4c9-11e7-9cfd-ab96b93e8217.png)

the run test case page could have the robot that was previously used but it comes empty.

Regards,
Cerberus Version : 1.1.15-SNAPSHOT-1237

**Comment by vertigo17** [comment]
In fact when you click on 'Run Test Case again', the default values for robot execution should be the one you are used to use. Could be your local instance of selenium.
In order to execute the test in the exact same parameter, you should use 'Duplicate New Execution'

![image](https://user-images.githubusercontent.com/5342048/31855610-e9ca3a90-b6ae-11e7-811e-e64d07a5b607.png)

And then click on 'Copy and Submit a new execution'

![image](https://user-images.githubusercontent.com/5342048/31855620-150005c8-b6af-11e7-8e06-e278e578c716.png)

This way you will have the exact same execution (including all parameters reused) inserted inside the queue for execution.

**Comment by vertigo17** [comment]
@j0hnsa, I close the issue as I guess Copy and Submit a new execution answer to your need.
Please reopen if you wanted something else.
