### ISSUE TITLE
Adding a bugtracker area in the "execution report by tag" page

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1528]
Hello, 

It would be interesting having a "Bugtracker Report" area zone in the "execution report by tag" page. The area would contains the following elements : 

- BugList with a link of the concerned bug detail page (Listing the different bugs opened) 
- The repetition of a bug (permit priorisation of a redundant detected bug) 
- TestCase Execution link (cf mock upl) or a testcasecript link (the link would be the first Execution/TestCase affected by the bug) 
- The Number of KO/FA and the total of bug opened => so we can calculate the  bug coverage ratio 

![buglist](https://user-images.githubusercontent.com/29098010/32319956-7a87d41e-bfbc-11e7-9bf9-c4a5998a295b.jpg)

**Comment by vertigo17** [comment]
I have a couple of question confirmation to ask:

- _BugList with a link of the concerned bug detail page (Listing the different bugs opened)_ 
- _The repetition of a bug (permit priorisation of a redundant detected bug)_ **- correspond to number of testcase where the same bug ID has been created on the corresponding tag execution.**
- _TestCase Execution link (cf mock upl) or a testcasecript link (the link would be the first Execution/TestCase affected by the bug)_ **- We need to choose so I suggest that we put any non OK execution that correspond to any testcase of the corresponding bugID**  
- _The Number of KO/FA and the total of bug opened => so we can calculate the  bug coverage ratio_ 
**On the example, KO/FA should be 0 and bug Opened should be 5. What should we display if there are no KO/FA ? Do you have in mind that bugId are open at testcase level and not execution level ? Souldn't we put nb of Testcase that have at least 1 non OK execution and nb of bug open so that target should always be 100%**

**Comment by Galand-V** [comment]
- The repetition of a bug (permit priorisation of a redundant detected bug) - _correspond to number of testcase where the same bug ID has been created on the corresponding tag execution._
**=> Yes, that what I had in mind. "TestCases Affected" would be a clearer title for user understanding**

=>I have in mind the fact that bugID are open to the testcaselevel. But it seemed to me that it was more precise to open a bug at the execution level because the  country/robot combinaison could impact the execution.

But in reality, this is maybe too specific to my organisation and some users do not use countries in Cerberus. So yes, link the TestCase associated should be the better solution. 

=> If  noKO/FA (**then no bug reported**) , the collapse could be close like screen attached. User will be aware of the feature, but it would not disburb users. what do you think ?

![image](https://user-images.githubusercontent.com/29098010/32368318-afe149dc-c085-11e7-8399-17ea16fa7cde.png)

Here is the new mock up : 


![buglist](https://user-images.githubusercontent.com/29098010/32370121-3813c4e6-c08c-11e7-8c23-f2497a816a87.jpg)
