### ISSUE TITLE
TC blocked in QUEUED State

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1534]
Hello,

When I run multiple TC or a campaing, every TC is in QUEUED State.

Clicking the "Save an submit again" button display a error message : 
"No record was updated. Unable to move state to QUEUD for execution in queue 33113 (update result: 0). Maybe execution is no longuer in CANCELLED or ERROR ?" 
![queued1](https://user-images.githubusercontent.com/27861047/32434458-748e4212-c2de-11e7-905e-2c4265feae27.png)

 Following, the parameters for the QUEUED state in Cerberus
![queued2](https://user-images.githubusercontent.com/27861047/32434459-74ae2e6a-c2de-11e7-9646-19372b32d70a.png)

**Comment by vertigo17** [comment]
Regarding the warning message on the modal, let me explain the usage of the modal buttons: 
'Save' button just save the new queue entry parameters. This is used to change the parameters on queue that are still open (ERROR, CANCELLED or QUEUED).
'Save and submit again' button does the same but also move the state to 'QUEUED'. That only make sense if the queue entry is not already in QUEUED State. This is used for CANCELLED or ERROR queue entry that you want to submit again. Because the entry is already in QUEUED, you have the warning message.
'Cancel' Just cancel the execution moving its state to CANCELLED

On top of that message, I understood that queue entry are not processed automatically and you need to click on 'Force Execution' in order to have them processed (even though there are no constrains for them to be executed).
That is probably linked with the fact that the job queue is not triggered.

In order to understand why that job is not triggered, I can tell you the event that trigger it in order to see if we miss 1. Job execute when any of those happen:
- Force Execution button clicked
- At the end of every execution (no matter coming from the queue)
- When inserting a new queue entry from the queue management screen.
- When updating a queue entry to QUEUED state
- When calling public API AddToExecutionQueue (all versions)

Can you confirm none of the event occurs when entry are not processed in queue ?
Can you also confirm that 'Job Start' timastamp in Queue Job Status tab is not updated (it contains the last time the job that process the queue was triggered). If that job date is moving but queue entry not processed it is probably because on constrain is blocking the execution.
