### ISSUE TITLE
Action hideKeyboard doesn't work on iOS

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1541]
Hi,

Don't know if it ever worked but it works on Android and now It would be useful to have on iOS too.

Regards

Cerberus Version : 1.1.15-SNAPSHOT-1237

**Comment by j0hnsa** [comment]
Alternatively I try to use Keypress ENTER but not always working:
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=52521486

**Comment by bcivel** [comment]
Hello @j0hnsa,

The problem is that the key hideKeyboard doesn't exist on IOS (in opposition with Android) . 
And regarding the context, a swipe or a click can allow to hide the Keyboard, but it's not always the same behavior. And we can't use ENTER because it use to hideKeyboard and submit the formulary.

I would advise to use another action to hide the keyboard regarding your context, like you already tried. 

Unfortunatelly, I don't think that we can implement in Cerberus something that will work for all context.

**Comment by vertigo17** [comment]
I close that as we cannot (even shouldn't) automate a feature that do not exist for end users.
