### ISSUE TITLE
Inherited properties being badly overwritten on CerberusQA (.30)

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1545]
Hi all,

I noticed that inherited properties are being badly overwritten in the test when selected just for one country inside the test, take a look at this example

http://192.168.135.30/CerberusQA/TestCaseExecution.jsp?executionId=39918099

property CONFIRM_DELIVERY exists inside this step lib for the 3 countries http://192.168.135.30/CerberusQA/TestCaseScript.jsp?test=MADIBA_APPS_LIB&testcase=0008D&step=2

on the test I overwrite for FR with a new value

http://192.168.135.30/CerberusQA/TestCaseScript.jsp?test=ANDROID&testcase=0003A_8.0_Sm&step=7&tabactive=tabProperties
If I change the overwritten property name to something else it retrieves the correct property for the other countries:

http://192.168.135.30/CerberusQA/TestCaseExecution.jsp?executionId=39918100

Can you check please?

Regards

Cerberus Version : 2.1.0-SNAPSHOT-1249

**Comment by vertigo17** [comment]
This behavior can be configured by parameter 'cerberus_property_countrylevelheritage'.

Parameter definition :
Boolean that activate the heritage of the property calculation at the country level. if N, a property will be considered as not available on country XXX when it does not exist for XXX and exist for any other country but XXX at testcase level (even if it has been defined at usestep or pretest level for that country XXX). If Y, it will be considered as defined for country XXX as long as it has been defined for that country at testcase, usestep or pretest level.

In your case the value is N so the CONFIRM_DELIVERY property is considered as undefined for RU because it was not defined at testcase level (even if it has been defined for RU in a inherited property)
