### ISSUE TITLE
Regression in data

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1555]
Hello,

We are working on a upgrade of our old Cerberus environment (1.1.15) to the latest version (2.X) but we're having a regression problem on the Environment Maintenance. 

In our current production, we have an environment (QA - FR) which is defined like this : 
![image](https://user-images.githubusercontent.com/30227758/32951672-13abc296-cbab-11e7-9a5b-50113c88773e.png)

It's possible to run testcases in this environment on our current production since the maintenance time slot is null (midnight to midnight).

But with the exact same environment dumped from the production DB in our temporary test system (in the latest version of Cerberus), we **cannot** add any related test in the queue. 
![image](https://user-images.githubusercontent.com/30227758/32951773-78db1a4a-cbab-11e7-8d30-e685ba5d20af.png)

Which shows that there is a behavior difference between Cerberus version 1.1.15 and latest one.

Workaround is pretty easy though : disable the maintenance.
![image](https://user-images.githubusercontent.com/30227758/32951874-c2c6d5c2-cbab-11e7-9138-b1bb8528b8aa.png)
 
Thanks!

**Comment by vertigo17** [comment]
I checked the feature and all seems to work fine.
It must be a data issue that I was not able to reproduce on my environment.
I added a better message so that in case it happened, it is easier to fix.
I will have to check the data in the database to see if an SQL is necessary to convert the data.

![image](https://user-images.githubusercontent.com/5342048/32992287-0fa60b9e-cd49-11e7-900a-6f74408df987.png)
