### ISSUE TITLE
Robot Selenium with Sikuli

### ISSUE THREAD

**Issue by SeniorCanard** [cerberustesting/cerberus-source#1561]
After visiting the Sikuli Cerberus page (https://github.com/cerberustesting/cerberus-extension-sikuli),  I have some questions about it.

Is the robot able to use both Selnium and Sikuli actions in a same TC ? 

It didn't see any installation needed on Cerberus, only on the robot server, is that correct? 

Do you know or recommend other options alike Sikuli?

Best Regards

**Comment by vertigo17** [comment]
Hello @SeniorCanard ,

_Is the robot able to use both Selnium and Sikuli actions in a same TC ?_
Yes you can use both. on actions like click, doubleclick, type, mouseover, wait, keypress, can use both engine. In order to force usage of sikuli, you need to identify element with picture=PATHTOPICTURE

_It didn't see any installation needed on Cerberus, only on the robot server, is that correct?_
Yes correct. Nothing to install on Cerberus side.

_Do you know or recommend other options alike Sikuli?_
No. Sikuli provide so far all the feature we required.
