### ISSUE TITLE
Export / Import a System

### ISSUE THREAD

**Issue by nicodeur** [cerberustesting/cerberus-source#1568]
Hi,

We developp an application with Cerberus Testing on an IT Service center. We would like deliver our cerberus test with the application to our customers.

It would be fine to have possibility to export all paramters / Application/ Test case of a System, and to can import them into another cerberus.

Regards,

Nicolas

**Comment by vertigo17** [comment]
@nicodeur , keep in mind that not 100% of the cerberus concept are linked with a system. Some of the concept that are not attached to a system : Test, Datalib, Service (most of the time linked with application though), Label (no longuer in order to allow them beeing transversal).
What could be done is an import / export at testcase level but that will still require testing to secure transversal concept are the same from 1 env to another.
I suggest we close that ticket to focus on import export only on testcase.
that ticket is duplicate from #1195 and #260

**Comment by nicodeur** [comment]
Hi @vertigo17 , I'm ok with you.

I close this ticket, but maybe can you modify prority of ticket #1195 ans #260 ?
