### ISSUE TITLE
Filters on ReportingExecutionByTag

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1578]
Hello,

I think it would be nice when we filter the executions on ReportingExecutionByTag to hide the QUEUE state tests if it would display the FA/KO of the already executed tests if the campaign was set to run with retries.

Regards

Cerberus Version : 1.1.15-SNAPSHOT-1237

**Comment by j0hnsa** [comment]
maybe a button to see last execution would be enough:

![imagem](https://user-images.githubusercontent.com/16339891/34104500-95dfc884-e3e8-11e7-8f4f-b49cf1add449.png)

**Comment by vertigo17** [comment]
Not sure I understand the issue.
Today, on reporting by tag page, the execution displayed for a given testcase, country, env and browser is displaying the latest entry whether QUEUED or execution.
That means that when an execution is submitted into Queue with 1 retry, the status will appear in the following status:
1/ QU QUEUED
2/ QU WAITING (too quick to see)
3/ QU STARTING (too quick to see)
4/ PE
5/ FA (too quick to see)
6/ QU QUEUED
7/ QU WAITING (too quick to see)
8/ QU STARTING (too quick to see)
9/ PE
10/ FA
1/ to 5/ correspond to 1st execution
6/ to 10/ correspond to second execution.
Do you mean that you would prefer to see the status FA from 6/ to 8/ ?
Not sure this is a good idea as in reality the execution is not FA but not yet finished.

On top of that, if you want to see history of past execution, you can use 'Last Execution with Country & Environment' from Execution detail page.
That will show you all last executions from that entry.

![image](https://user-images.githubusercontent.com/5342048/34272781-f3a43a08-e691-11e7-85e6-a7e92bf60d99.png)

**Comment by j0hnsa** [comment]
Mainly I launch the campaigns with one retry and when a test fails it'll go to the state QUEUE again and in order to see why it have failed we have to do a couple of clicks like opening the Edit TC and then filter the last executions and then open the last exec.. This could save some time In my understanding. But its just a proposal...

Regards

**Comment by vertigo17** [comment]
Not sure if you knew it but you already have the information on the popup that report the total nb of execution hat was triggered (only appear if >1).

![image](https://user-images.githubusercontent.com/5342048/34464640-d18e542c-ee88-11e7-9f4a-6401d482972c.png)
On that once, 11 executions were necessary to get the OK.

I also added a new column on the report in order to sum all those retry per testcase. You can use it in order to sort to get the testcases that require the most to be executed many times.

![image](https://user-images.githubusercontent.com/5342048/34464648-687af8fe-ee89-11e7-9506-49ab8fd4d300.png)

Once it happens, you will still need to open the corresponding execution and get to the 'Last Execution with Environment & Country' in order to see all of them.
