### ISSUE TITLE
Cleanup process for DONE executions on TestCaseExecutionQueueList

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1584]
Hello,

TestCaseExecutionQueueList is getting quite heavy to load and I was wondering if we should implement some cleanup like DONE executions older than 1-2 days? Because at the moment we have 
"Showing 1 to 50 of 1,068,365 entries"

Cerberus Version : 1.1.15-SNAPSHOT-1237

**Comment by vertigo17** [comment]
Yes this is for sure necessary.

Standard purge script has been updated in order to enrish the SQL that is supposed to purge that data:
https://github.com/cerberustesting/cerberus-source/blob/master/tools/SQLscripts/CerberusDatabaseScriptPurge.sql
It already provide 
1/ a global purge after 100 days 
2/ a purge after 10 days of queue entries that never manage to trigger any executions

I will add one that perform a purge after 10 days of DONE executions:

DELETE FROM testcaseexecutionqueue
where TO_DAYS(NOW()) - TO_DAYS(DateCreated) >= 10 and State = 'DONE' ;

Just keep in mind that if you purge it too soon, you loose the ability to relaunch a testcase directly from the queue (without feeding all executions parameters). This is for me in important feature to re execute a testcase in the very same context in a safe way.
![2018-01-04 13_12_39-execution detail](https://user-images.githubusercontent.com/5342048/34562977-964ad01c-f148-11e7-9b13-b9abae5099d4.png)

In my opinion you should keep around 10 days.

What can be done as well is to optimise the performance of the screen without beeing forced to purge the table. Let's keep that issue open until screen is optimised (access by tag filter optimisation can be imporved).
