### ISSUE TITLE
Test cases out of the build range are added to the queue execution

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1607]
Hi,
Test cases out of the build range are added to the queue execution.

When test case are set to be executed to a specific Build/revision:
![image](https://user-images.githubusercontent.com/17747042/35931048-835c5c2a-0c2b-11e8-88c2-68fc406c5d59.png)
In this case the current build/revision is:
![image](https://user-images.githubusercontent.com/17747042/35931678-3c814732-0c2d-11e8-8d46-d815c5d36078.png)

 
Nonetheless the test is added to Cerberus queue system but the ends in error:
![image](https://user-images.githubusercontent.com/17747042/35931199-defe53bc-0c2b-11e8-98bf-127a0fae9301.png)
![image](https://user-images.githubusercontent.com/17747042/35931208-e87a7c86-0c2b-11e8-8585-2542277f4d56.png)

If the test case is out of the range it should not be added to the queue.
Note that the campaign used to execute the test is based on the system and on the test case status.

Cerberus version: 3.1.0-SNAPSHOT-1286

**Comment by vertigo17** [comment]
Hello @ffazendeiro , I am not sure this is the best option as in this case, the execution will 'disappear' without any notification from user.
Adding them to the queue has 2 advantages:
- Notify the users that version does not allow to execute the test.
- Allow the user to correct the version of the environment or constrain of the testcase in order to resubmit the execution.
What do you think about it ?

**Comment by vertigo17** [comment]
A new status will be implemented for that.
