### ISSUE TITLE
Can't cancel a retry from the execution queue

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1620]
Hello,

It seems that we are unable to cancel executions in the queue:

![imagem](https://user-images.githubusercontent.com/16339891/36377051-6f78688e-156d-11e8-9951-c8159d357f75.png)

also if we try to rerun from the queue changing the robot the new robot will not be selected

![imagem](https://user-images.githubusercontent.com/16339891/36377107-afa4698a-156d-11e8-98cb-7f3ecd528389.png)
![imagem](https://user-images.githubusercontent.com/16339891/36377120-c1a78360-156d-11e8-9b5e-a68d4e970547.png)

Cerberus Version : 3.1.0-SNAPSHOT-1286

**Comment by vertigo17** [comment]
For the 1st issue, I was not able to reproduce. What could have happen is if you click before the testcase combo loads, it will report beeing missing. Waiting a bit and clicking again fix the issue. Does it reproduce systematicly for a given execution id ? Is it only when Cancel or also on save ?

For the 2nd issue, the detail of the execution is not displayed until the execution start. That include robot tab that will stay empty until execution start. In order to avoid the confusion, I hide tab section.
I can confirm that when the execution starts, the correct robot is selected (even if screen stay empty).

**Comment by vertigo17** [comment]
it will look like that for a CANCELLED execution:
![image](https://user-images.githubusercontent.com/5342048/36395555-08da7dcc-15ba-11e8-9f6f-fd73bae95413.png)

like that for a QUEUED execution:
![image](https://user-images.githubusercontent.com/5342048/36395602-3ada31e6-15ba-11e8-98c3-ddefaf5a89d6.png)
