### ISSUE TITLE
Test case vanishes when test case is changed

### ISSUE THREAD

**Issue by gmoita** [cerberustesting/cerberus-source#1626]
We updated a test case with a new test and test vanishes.

Steps to reproduce:
1) old test case ICS_CREDIT/0005D, when test ICS_CREDIT is renamed to ICS_Credit (don't know when it was done)
2) We went to the Test case list page and selected the button to Edit Test case header
3) Test drop down field was shown empty
4) Selected the test "ICS_Credit" available on the drop down list
5) View the warning message saying that all the test case executions history will be lost
6) Confirmed the action
7) Verified that test case vanished; also verified on the database and testcase table lost data for this test case
8) Verified logs of glassfish server and no messages found
9) Repeated the same actions with latest Cerberus snapshot version and problem is the same
10) Confirmed that no logs were created when doing these actions also on QA server

Despite the execution history is still kept on the old test case naming "ICS_CREDIT/0005D", the test case information simply disappears from the database.

I believe that this is a very critical issue.
Please confirm the behaviour.

**Comment by Nouxx** [comment]
Hello,

> Verified that test case vanished

@gmoita, what do you mean by 'vanished'?

I already faced a similar issue in the past, modifying the **Test** name made all the belonging **TestCase** scripts impossible to edit or run (Internal Server Error). The problem was that the modification wasn't propagated everywhere in the DB : the **properties** or the **steps** (can't remember) were still linked to the old **Test** name which caused data consistency issues.
The solution was either : updating in DB or rename the **Test** to its old value.

Here's what was able to reproduce on our lastest environment: 

- Rename a Test including only one empty TestCase (1 empty step) : success
- Rename a Test including several TC and properties : the following error occured. 
![image](https://user-images.githubusercontent.com/30227758/36489879-55c113bc-1727-11e8-918b-9d92ae8f7e4a.png)
I wasn't able to rename it, even with different combination

These two attempts are not enough to make any conclusion, but hopefully it can help.

**Comment by gmoita** [comment]
Problem is that current testcase ICS_CREDIT (test column) should be ICS_Credit, which exists on the test table.
Test case is really deleted from the tables; I've searched directly on the database and data is not there.

**Comment by gmoita** [comment]
I've just replicated the behaviour on QA... data from tables testcase + testcasestep + testcasecountry + testcasecountryproperties disappears.
I've checked with selecting only the testcase ID and only thing keps it execution data on the old test.

**Comment by Nouxx** [comment]
Here's the solution:

Context:
- In your **Test** 'ICS_Credit', one of the **TestCase** (the 0005D) was linked to a 'ICS_CREDIT' **Test** which doesn't exist (the root cause hasn't been identified)

Step to reproduce:
- in the UI > Edit TC Header > select 'ICS_Credit' **Test**

The TestCase ID was renamed in 0037A, instead of 0005D and was linked to the right Test ('ICS_Credit')

After a deeper analysis with @gmoita, we found out that the last **TestCase ID** was 0036A and by changing the **Test** on the 0005D, Cerberus might have considered it as a new **TestCase** and increment its ID to the last possible value (in this 0037A).

The workaround is simply to rename the 0037A back to 0005D and even the execution will be preserved.

Thanks!
