### ISSUE TITLE
% not support in application object

### ISSUE THREAD

**Issue by Ryu26** [cerberustesting/cerberus-source#1640]
For a project in multi country, I have 2 type of ID for the same object :  
Example : 
- "luxembourg/onboarding_slide_btn"
- "pologne/onboarding_slide_btn" (See Screenshot)

![config_cerberus_application](https://user-images.githubusercontent.com/37080589/36989024-be52e55e-20a0-11e8-9f8d-b3b60b1fa7e5.PNG)

However the country, i want to create a parameter like "%system.APP_VAR1%onboarding_slide_btn" in label for each "id" but **caracter "%" is not support in application object.**

It is possible to add this functionality in the next release ?

**Comment by ryltar** [comment]
Hi @Ryu26 , where do u want to create the parameter "%system.APP_VAR1%onboarding_slide_btn" ? I don't really understand what you want to do :(

**Comment by vertigo17** [comment]
Just fixed the issue of not being able to put a % inside the values field of applicationobject.
I would also advise to use %system.COUNTRYGP1% in order to save the 'luxembourg' value instead of %system.APP_VAR1% that will force you to configure 'luxembourg' for all application...
Values GP1 to GP9 can be configured under invariant menu for each country.

![image](https://user-images.githubusercontent.com/5342048/37174650-70437008-2317-11e8-86d0-1599e51eeb3b.png)
