### ISSUE TITLE
Condition operator in test case header using a property is not working

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#1650]
Hi
If we use a property defined in the test case to validate if the test should be executed or not using the Condition operator in header we get the error message "_The test case failed to be executed. More lickely due to an error in the test or in cerberus configuration. Exception: java.lang.ArrayIndexOutOfBoundsException_" and the test execution result is FA:

![image](https://user-images.githubusercontent.com/17747042/37300825-e3c6086a-261e-11e8-8c64-06ef536241f4.png)
Note that property PREVIEW_UK_DONT is defined in the test case.
In the previous Cerberus version this was working fine.

Also did some manual test and if the condition is not true, the test case execution will be FA. In the previous version the test case was not executed (no execution number) if the condition was not true. Is this a new behavior?

Cerberus revision: 3.3-SNAPSHOT-1300

**Comment by vertigo17** [comment]
Expected behaviour is that the execution is created with NA return Code and the message explaining why the execution could not start.
This is not supposed to be a new behaviour but maybe there were an old bug there.

![image](https://user-images.githubusercontent.com/5342048/37869174-58b6b4c4-2fb3-11e8-97e6-64d7e09957a7.png)
