### ISSUE TITLE
campaing criteria/parameter sugestion

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1668]
I think this is not currently possible and we discussed the following ideia: 

would it be possible to add more criteria/paramenters to a campaign including personalized data and that be acessible in the testcase with something like %campaign.parameter1%? 

it would be useful to create testcase variations in some spefic subjects according to campagain data.

Thanks!!

**Comment by vertigo17** [comment]
Good idea.
We already have a ticket in order to add the possibility to create properties from execution request:
https://github.com/cerberustesting/cerberus-source/issues/1401

We could add that feature to AddToExecutionQueue Servlet that would keep that list of property / value into a json structure saved inside the queue table.
That structure would be parsed to be send to runtestcase servlet that would create on the fly property with corresponding values.

We could define that same json data inside campaign with the same result.

JSON would look like:
{
  "key1": "value1",
  "key2": "value2",
  "key3": "value3"
}

Query String sent to AddToExecutionQueue or RunTestCase servlet would look like:
RunTestCase?property.key1=value1&property.key2=value2&property.key3=value3

**Comment by lucashimpens** [comment]
Issue linked to #1401 so we close the ticket. (La Redoute)
