### ISSUE TITLE
Issue with DELETE method API call

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#1670]
Hello,

For API method Delete, the service request (screenshot 1) is placed in the calledURL instead of the http request. (screenshot 2). So we got the following error : "message":"Required request body is missing
modelCodes = [11111,22222]
Screenshot1:
![image](https://user-images.githubusercontent.com/18569182/38237505-ac38012c-3727-11e8-9a02-692a68632c27.png)

Screenshot2:
![image](https://user-images.githubusercontent.com/18569182/38237685-2611048a-3728-11e8-8783-0de22c948b2b.png)

If needed, the service detail : 
![image](https://user-images.githubusercontent.com/18569182/38237488-a02c39d4-3727-11e8-9c9b-60a42a3519b3.png)

Could you please check this issue ?
Thanks !

Cerberus Version : 3.2-1296

**Comment by Galand-V** [comment]
+1

**Comment by evanemh** [comment]
+1
Same issue here - our tests are high priority so we are blocked until the issue is fixed.

When trying to test my API with DELETE verb, I have the error below:
"Failed to call the Service 'DELETE Delete reference'. Caused by : Error on CallREST : java.lang.IllegalArgumentException: Illegal character in query at index 36: https://my-api-endpoint/my-resource?{my-json}."

Cerberus is calling the endpoint by putting the json request in the parameters (by adding "?" at the end) instead of in the body.
It is working correctly for the PUT verb tough.

**Comment by vertigo17** [comment]
Last commit should fix the issue. If you can confirm it works (DELETE normaly does not allow to send request Entity so I had to tweak the call from a POST format).
Please @R-Loic and @evanemh confirm that it works on your side.
