### ISSUE TITLE
Robot declination applied on queued tests (grouped like they were before)

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1673]
Would it be possible to apply the same behavior on tests that are on queue and the others that we're already executed? I'm using 6 robots and the look of the report meanwhile the execution it is very confusing...

![imagem](https://user-images.githubusercontent.com/16339891/38253362-61936298-374e-11e8-9709-1b4994b164d5.png)

![imagem](https://user-images.githubusercontent.com/16339891/38253389-7016f69a-374e-11e8-9a4c-edc28b366ff3.png)

Cerberus Version : 3.4-SNAPSHOT-1319

**Comment by vertigo17** [comment]
If I understand correctly, You submit the execution to Robot : Smartphone-GRID-v8 that has %BROWSER% as declination.
As long as the execution is in the queue the report display Smartphone-GRID-v8 but when execution is triggered, it changes to an empty string that correspond to the browser (if it is an IOS application, that looks normal).

Not clear on what you expect.

If you want to always display Smartphone-GRID-v8, just empty the robot decli data. Once execution trigger, it will keep the robot name as the robot value.
If you want it to be always the same but not Smartphone-GRID-v8, you will have to put the static value in decli (don't use %VARIABLE% as those can only be replaced once execution start and we can really check what was used by Selenium/appium in terms of browser, platform, version and screensize).

We could change so that Robot Decli is used at queue level (in stead of Robot name) but anytime you use variable, it will still be replaced from '%BROWSER%' to the real robot when execution start .

**Comment by j0hnsa** [comment]
What I would like would be to have the display on the same column before and after the test is executed

I've placed a static text on robot decli and it still displays on different columns:
![imagem](https://user-images.githubusercontent.com/16339891/38259795-d6faa5a0-375d-11e8-83dc-c20cfe4b2ada.png)

Also it was noticed on today's preprod analysis some cases where an execution in error would be still displayed even with an OK execution afterwards (in different columns).

Is it possible? How? 

Thanks and Regards
