### ISSUE TITLE
Test cases stuck in queue

### ISSUE THREAD

**Issue by htopoff** [cerberustesting/cerberus-source#1697]
Hi,

When I add more than 1 case in the queue, the TC stack up but nothing hapends.
![2018-04-19 14_53_37-executions in queue](https://user-images.githubusercontent.com/38133450/38992731-ed0cec5a-43e1-11e8-8dd2-ef39ecc2f9b5.png)
The TC are staying in QU state.

Help me please !
Thank you.

**Comment by vertigo17** [comment]
Have you tried to force execution from the Queue Job Status ?

![2018-04-19 14_59_39-executions in queue](https://user-images.githubusercontent.com/5342048/38992885-9cde5a8a-43d1-11e8-95c7-3537ca7e7e4f.png)

When was the last execution Queue Job Start date ?
It correspond to the last time queue has been checked in order to potencially release some execution.
If you have very few executions and all of them in ERROR, it could happen that execution are not triggered.

**Comment by htopoff** [comment]
It worked !
Thank you ;)
