### ISSUE TITLE
Integrate with a code repository

### ISSUE THREAD

**Issue by Sir4ur0n** [cerberustesting/cerberus-source#1704]
Hello,

We're considering integrating Cerberus with our workflow, however like many new modular projects we have a simple Git workflow:
- a single infinite branch (master)
- each PR comes from and goes into master

In particular, we strive for Continuous Deployment, and we consider `master` to be our "prod ready" branch, and want to be able to deploy it any time (every day / hour / minute).

We do not wish to have several infinite branches (e.g. `develop`) as they bring much more problems than they solve (cascading, cherry picking, hotfix, etc.).

In this context, we want to run all our Cerberus tests in each PR. In short, in each PR, we currently compile, run unit tests, deploy a short-lived platform. We now want to run the Cerberus tests so that a build success in a PR guarantees this is Prod ready.

Ideally, we want to version all the Cerberus tests with our code, so that the tests to run for each PR is directly contained in the code being built/deployed. AFAIK (and I had a chat with some Cerberus developers) it's not (currently?) possible with Cerberus.

A fallback, acceptable solution may be to have an easy way to import/export tests so that in our build flow, we can import all our versioned tests and execute them (and decide if the build is a success accordingly) while being able to write/update tests easily in Cerberus (we really like the UI) and then export them back into our code.

1. Does that make sense?
2. Is that a considered feature of Cerberus? 
3. If yes, any idea on the release date? 
4. If yes, what kind of contribution would help? Keep in mind we (my team) are huge Cerberus noobies 😃 

Cheers

**Comment by vertigo17** [comment]
I fully agree and 100% inline with the vision you explain. In fact, Cerberus use that type of dev strat, Our master is also targeted as being ready for prod and always stable.
We also deploy in a QA environment every single push. The only thing that differ is that we do not build an environment on the fly but on a static env  (we don't commit that often) and also only trigger the Cerberus campaign once a day and not on every commit (the reason is more linked with BrowserStack constrain where have a free license that does not allow us to execute for each commit).

As a consequence, you can trigger the Cerberus campaign after every deploy (even pointing to a specific environment in case the env connection URL is defined on the fly). You can then get the result immediately and attach that result to the build or even better save the tag executed from the pipe to the release.
In fact I may miss something but I don't understand what is the interest to version all tests with the code considering that in the end you will get back to master for each changes and trigger a new campaign from the latest version of each test that can stay inside Cerberus.
Cerberus potencially allow you to keep a version id attached to the environment in order to keep for each test the version of the application that has been tested.

Anyway, we already have a ticket in order to do the import/export of testcases inside a json structure but that is not that easy considering that a testcases can point to services, objects, labels and datalibs that have their own definition. 
Answering your question: yes the export/import make sense and is considered as being a target feature of Cerberus although we don't have dates yet for that.

As mentioned before, I don't think this is a mandatory feature for your need and we should probably need to discuss on your need or even better meet to share your need where Cerberus needs to adapt as I share your vision and Cerberus should support it 100%.
Can we get n touch in order to share on the subject ?

**Comment by vertigo17** [comment]
We shared with @R-Loic and @nicodeur and even if export / import feature is still in the roadmap, the idea of the tool is to stay integrated from the database that allow easy access and management from end users.
TestCase are linked to many other centralised objects/ Datalib and services that allow high level of factorisation. Having things managed by code repository means removing that capabilities that are key to implement a user friendly testing tool. 
Tool is more to automatic test the master branch.

**Comment by Sir4ur0n** [comment]
Alright, I think this settles the discussion, thank you!
