### ISSUE TITLE
Method to get window size or device name for appium tests

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1708]
Hello,

I would like to have some way to get the window size or device name on the android apps. We have now some different resolutions on the devices we have ,and sometimes, to workaround some other issues we use coordinate clicks. With different screensizes this will not work. Can we have some way to obtain this info during the test?
Thanks in advance
Regards,
Cerberus Version : 3.4-SNAPSHOT-1319

**Comment by vertigo17** [comment]
I suggest we create a new system variable in order to get the x and y resolution for all application type (GUI, APK, IPA, FAT)
system variable syntax would be:
%system.resolution.width%
%system.resolution.heigth%
OK ?

Maybe we could also rework the way we provide the coordinates in order to avoid beeing forced to make some calculation based on width and height. (on a separate ticket)
