### ISSUE TITLE
Launch one testcase several time simultaneous

### ISSUE THREAD

**Issue by htopoff** [cerberustesting/cerberus-source#1711]
Hi,

I want to launch a testcase a multiple of time simultaneous for a charge test.
That's a web application.

How can I do that ?

**Comment by Nouxx** [comment]
Hi @htopoff ,

The easiest way would be to duplicate the actual Test Case several time, and regroup all of them in a campaign, then launch it. Be aware of increasing your pool size to match the number of Test Case that you want to launch simultaneously.

You can also use your Selenium Hub to launch a specific campaign every X seconds. I'm not really familiar with this topic though, so I'm not even sure it's possible.

Those solutions are not really convenient, but Cerberus is designed to perform 'functionnal' tests for an application. Consequently, it will not be well-suited for bulk tests.

**Comment by vertigo17** [comment]
Another way could be to call the /AddToExecutionQueue Public servlet as many times as you need executions. a script with massive curl command could do the job.

Like Nouxx mentionned Cerberus will try in anycase to trigger the executions as fast as it can depending on the constrain. If you want to manage rammup and down, you will have to do it manually modifying the constrain parameter in the right timing.
Althought it is possible to stress test an application with it, it is not its main purpose.

**Comment by htopoff** [comment]
Hi,

Thank you for your answers,
I tried to duplicate my test and put all of them in a campaign but it didn't worked.
It ran only the first one...

I'll try the script with /AddToExecutionQueue now ;)

Any other suggestions ?

**Comment by vertigo17** [comment]
There are no reason for the testcases in campaign do not execute. 
Are the executions in the queue ?
Are there any error message reported ?

**Comment by htopoff** [comment]
There is only one execution in the queue.
No error message, test is "Done" and "OK"

**Comment by vertigo17** [comment]
If you execute in Prod environment, have you checked that the active flags for duplicated test are all active ?
By default those are inactive and preventing test to be executed by mistake in PROD.

**Comment by htopoff** [comment]
Yes, I'm executing in Prod env.
Where is this flag ?

**Comment by Nouxx** [comment]
In the Test Case Header
![image](https://user-images.githubusercontent.com/30227758/39349116-10946afe-49fa-11e8-8ab8-ba04a2221c1c.png)

**Comment by htopoff** [comment]
Well, it worked !
Thanks for your help ! ;)

**Comment by htopoff** [comment]
Hi,
When I launch my campaign or when I do "/AddToExecutionQueue" only 4 tests are executing simultaneously. 
The other ones are waiting in "Queued" state. They start one by one when the previous tests are over...
I changed the pool size value but it seems like there is a limit somewhere else.

**Comment by vertigo17** [comment]
In order to get the information of Cerberus on why the execution are not released, you have 2 options:

Either follow the constrain activation on the 'Pool Followup' TAB:
![2018-05-23 12_19_16-executions in queue](https://user-images.githubusercontent.com/5342048/40418794-d202aea8-5e72-11e8-8cb1-f1daf5fd6c9a.png)
Sort by 'nb of execution over saturated queue' descending and it will tell you the constrain that limit the execution.
In that case 4 constrains all at robot level limit the execution of the queue.

Either modify an execution in the queue and activate the 'Debug Flag' to Y:
![2018-05-23 12_16_40-executions in queue](https://user-images.githubusercontent.com/5342048/40418972-54c1c9e6-5e73-11e8-95a4-b54b0cd543db.png)
It will then feed the reason why execution stay on queue.
![2018-05-23 12_22_11-executions in queue](https://user-images.githubusercontent.com/5342048/40418989-652b429e-5e73-11e8-8d93-65cd204bec90.png)

**Comment by htopoff** [comment]
First option worked, a global pool size was set on "4" !
Thank you.
