### ISSUE TITLE
implement scrollTo action for Selenium

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1736]
Hi, 
following the subject discussed by email with Clement, i'm not sure if the auto scroll on click was really implemented in the last release. 
Can you please clarify this sutiation? Thanks!

> -	The older versions of web browsers (i.e the Firefox version that we are using) aren’t following the latest W3C guidelines, which means that the rendering in Selenium is for the whole page. The latest versions (which are aligned to W3C guidelines) are only rendering a certain part of the page (according to the screen resolution). That’s why we have to scroll on latest Chrome and not in the old Firefox ones.
Thanks @DUMONT Benoit to bring this insight! We are considering reworking the click action in Cerberus so that it automatically scrolls to the actual element if it isn’t in the “frame” so that you don’t have to bother add loop in Cerberus. I’ll give a try with your code. What do you think?

**Comment by vertigo17** [comment]
Not it is not. What has been implemented recently is scrollTo action.
Is that required ?
Can you confirm that the real need behind this is not to systematicly scroll on click (or many other actions) but more to scroll when we perform the screenshot in order to see what happen during the test.
I didn't test on my side what happens on Cerberus when an action fail on a hughe page and on a recent browser that is only able to render the page where the screen is.
Have you made that test to see how it looks today ?

**Comment by vertigo17** [comment]
Sorry Rui, Basicly I ask you to detail what you expect within this ticket ?
what do you mean by click + scroll ? What is it and what is that for ?

Indeed screenshot is a different subject that I beleive we mixed and if relevant should appear on a different issue.
