### ISSUE TITLE
Multiple executions after canceling retry

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1752]
If we launch a campaign with 1 retry for instance and after the first run we decide to cancel the retry's that are still on the Queue, then, when we retry a failling testcase afterwards it'll run twice (at least if it fails).

Regards
Cerberus Version : 3.5-SNAPSHOT-1335

**Comment by vertigo17** [comment]
The way it works is that 
1/ When execution is submited, a Queue entry is created
2/ QueueEntry gets processed and submit the execution. queue entry move to EXECUTING
3/ At the end of the execution the Queue entry move to DONE
4/ If execution result is <> OK, a new queue entry is input into the queue.

If I understand right, you move the queue entry during the execution from EXECUTING to CANCELLED (between 2/ and 3/) and expect that after 4/, system does not submit because queue entry is in CANCELLED mode.
