### ISSUE TITLE
The step Creating RunId is sometimes infinite

### ISSUE THREAD

**Issue by GrandjeanRemi** [cerberustesting/cerberus-source#1768]
Hello,

When i run a test case, the step "Creating runId" take a lot of time (2-3 min) or is infinite. However the test case is well in the queue.
![image](https://user-images.githubusercontent.com/36671939/41976175-b25a6396-7a1c-11e8-90a0-e06a6497461d.png)
![image](https://user-images.githubusercontent.com/36671939/41976188-bf997c86-7a1c-11e8-893a-de27a122fe53.png)

I have to kill the test case in the execution queue and rerun it to it works fine. 
This problem increase a lot the execution time of our campaign, can you check that please ?

Thanks

Rémi.

Cerberus3.6-1350

**Comment by vertigo17** [comment]
This is more lickely due to the fact that Cerberus does not manage to connect to remot Robot.
If you wait a bit more you will probably see on the execution the timeout error on the http connection to the robot.
I will change the message so that it reports that it tries to connect to the robot in order to better understand what is going on but in order to fix the issue, you probably need to check the connectivity from Cerberus to robot.
What we could also improve is to setup a timeout in order to avoid waiting for too long.
Can you tell me how long it took at the end to release the execution ?

**Comment by GrandjeanRemi** [comment]
Thank's for your answer. 

I wait approximately 7-10 min before displaying an error message.

Rémi.

**Comment by vertigo17** [comment]
new parameter cerberus_robot_timeout has been created (default to 60000, ie 1 minute).
That will avoid loosing the 7 to 10 minutes before the retry.
The message is also more clear on that step of the execution.

**Comment by vertigo17** [comment]
That feature for Appium will have to be rollback in next release.
Appium Client library has a bug that prevent proxy and timeout setup to work properly.
@ryltar , if you can reference the Appium issue from here so that we can follow up its implementation ?

**Comment by vertigo17** [comment]
I found it back : 
https://github.com/appium/java-client/issues/854
