### ISSUE TITLE
API Service & HTTPS Handling

### ISSUE THREAD

**Issue by Dest69** [cerberustesting/cerberus-source#1772]
Hello guys, 

I encoutered an issue with API call on HTTPS URL. 

Indeed, I created a service (named "Login") to make a POST API call on an URI protected by a certificate. When I executed it, it throwed this error :
`Failed to call the Service 'Login'. Caused by : Error on CallREST : javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.`

It seems that Cerberus doesn't handle HTTPS properly. Does anyone already encountered this issue ? 

Thank you for your concideration

**Comment by vertigo17** [comment]
Do you have a sample https service available over Internet that we can use for testing purpose ?

**Comment by Dest69** [comment]
Nop, sorry, I can't give you access to this API... 
With a quick search, I found a way to mock an API with HTTPS : https://jsonplaceholder.typicode.com/

**Comment by nicodeur** [comment]
Hello @Dest69 ,

Can you test with an other https api ?

I try to reproduce your problem with https://www.googleapis.com/youtube/v3/channels?part=contentDetails&mine=true . API, and it's work fine ...  Can you test with it ?

![image](https://user-images.githubusercontent.com/6707556/42043543-00b11e06-7af7-11e8-82ca-e04d6f4176ca.png)

`Response` should be 
```
{
  "error": {
    "errors": [{
      "domain": "usageLimits",
      "reason": "dailyLimitExceededUnreg",
      "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
      "extendedHelp": "https://code.google.com/apis/console"
    }],
    "code": 403,
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
  }
}
```

**Comment by Dest69** [comment]
I tried, with success (got the same answer as you do)...

**Comment by nicodeur** [comment]
I succeed to reproduce the problem with an non valid https url.

According to this link : https://www.developpez.net/forums/d922760/java/general-java/apis/securite/erreur-suncertpathbuilderexception-unable-to-find-valid-certification-path-to-request/, problem is due to java accept only the commons and known certificat (`pki`).

Probably, your certificat is not known by java, So 3 possiblities : 
* Added your certificat on the java truststore (the more secure, but Cerberus can't test non signed ssl whit this solution),
* Authorize all (with thist solution by exemple : https://stackoverflow.com/questions/2703161/how-to-ignore-ssl-certificate-errors-in-apache-httpclient-4-0), but need a new release of cerberus
* Leave the choice to the Cerberus user or Cerberus administrateur to use the good method ...

@bcivel , @vertigo17 what do you think about it ?

Nicolas

**Comment by vertigo17** [comment]
I prefer the option to leave the choice to the users.
We should implement a trustAllCertificate flag that could be defined at system level (by a parameter) and service level.
By default we should default parameter to trust All Certificate still allowing administrator to not trust.
And also leave the users at service level to change this behaviour.
We could start the implementation only with the parameter (as require no database change).
