### ISSUE TITLE
Execution campaign test

### ISSUE THREAD

**Issue by FRBON** [cerberustesting/cerberus-source#1797]
Cerberus Version  3.4-1335

If i run the test one alone (panneau configuration) : all is OK

![image](https://user-images.githubusercontent.com/40494434/42943970-ad626a92-8b64-11e8-9e5c-aed3e8236e98.png)

If i run test numebr two (pointeur souris) alone : all is OK

![image](https://user-images.githubusercontent.com/40494434/42943916-7cf73a54-8b64-11e8-81df-a6190157f591.png)

But if i run a campaign with the two tests 

![image](https://user-images.githubusercontent.com/40494434/42944115-1334b23a-8b65-11e8-9537-9f8ee34d880b.png)

The result is :    

![image](https://user-images.githubusercontent.com/40494434/42944537-31a92e48-8b66-11e8-9882-3fce1a03fa93.png)

![image](https://user-images.githubusercontent.com/40494434/42944570-4b9740e2-8b66-11e8-8e5e-6ff456059eb0.png)

action 1.1 et action 1.2 give this

![image](https://user-images.githubusercontent.com/40494434/42944837-05d13346-8b67-11e8-9ef0-f70e62311a8e.png)

Panneau is not enter in the zone of research

**Comment by vertigo17** [comment]
Looks like the 2 testcases are executed at the same time on the same robot.
If you execute both tests at the same time, sikuli will get confused and perform actions from the 2 different testcases at the same time with random and weird results.
If this is the case, you need to add a constrain at robothost level in order to secure that for that host, only 1 testcase will be executed at a time.
To do that create the following invariant:
![image](https://user-images.githubusercontent.com/5342048/42965488-748617c4-8b9a-11e8-8000-759058cfe7e4.png)

just replace 'localhost' on value field by the host/ip that you defined on you robot.
and 10 in group 1 field by 1 in order to specify that only 1 execution at a time on that host.

**Comment by FRBON** [comment]
Thank you


before doing the modification I would like how it is possible that the two processes execute at the same time since I put the following parameter concerning the threads

![image](https://user-images.githubusercontent.com/40494434/42992378-a61ecdc6-8c08-11e8-8a75-ebaef42ac850.png)

**Comment by FRBON** [comment]
To take into account the modification during a launch, it is necessary to put somewhere ROBOTHOST when i run campaign ?

usually I run like this :     

![image](https://user-images.githubusercontent.com/40494434/42994393-4718dcee-8c0e-11e8-9d6e-d83a9cdb6777.png)

**Comment by vertigo17** [comment]
Simultaneous execution was an hypothesis.
Setting the parameters at 1 should secure that 1 execution is triggered at a time.
Considering that you submit the execution on localhost, that should be quite easy to confirm that hypothesis. Can you confirm that ?

**Comment by FRBON** [comment]
L'execution de la campagne suivante 

![image](https://user-images.githubusercontent.com/40494434/43008266-e1da7c34-8c3a-11e8-8b8a-d14d393cf203.png)


![image](https://user-images.githubusercontent.com/40494434/43008240-cd9f7d1e-8c3a-11e8-8183-d2ca47cb013f.png)

give :  

![image](https://user-images.githubusercontent.com/40494434/43008354-21819688-8c3b-11e8-974f-33911f7c734c.png)

So i have to put the two paraméters thread = 1  :    

![image](https://user-images.githubusercontent.com/40494434/43008425-59b1769a-8c3b-11e8-8da3-6198ac8e7b61.png)


**and define ROBOTHOST like this :**  

![image](https://user-images.githubusercontent.com/40494434/43008410-4990def4-8c3b-11e8-9450-2e1e05a77c5d.png)

**Comment by FRBON** [comment]
yes thank you the problem has been solved
