### ISSUE TITLE
How works manualHost in a jenkinsfiles ?

### ISSUE THREAD

**Issue by GrandjeanRemi** [cerberustesting/cerberus-source#1819]
Hello,

I want to run a cerberus campaign from a jenkins files with a manualUrl for a rest application: 

```
pipeline {	
	agent any
		stages {
			stage('Run Cerberus nrt') { 
				steps{ 
					executeCerberusCampaign campaignName : "GS-REST", tag : "GS-REST-${BUILD_NUMBER}", browser : "" , environment : "", screenshot : "1", verbose : "1", pageSource : "1", seleniumLog : "1", timeOut : "30000", retries : "1", ss_p : "", ssIp : "",robot : "SeleniumPreprod", priority : "", manualHost: "http://gs-rest-feature.***.org", manualContextRoot: "/", country: "", cerberusUrl: ""
				} 
			}
		}
}
```

When i look the console output, i have the following call : 

`Trigger Cerberus call : https://cerberus.*****.org/Cerberus/AddToExecutionQueueV003 with query String : campaign=GS-REST&tag=GS-REST-46&robot=SeleniumPreprod&screenshot=1&verbose=1&pagesource=1&seleniumlog=1&timeout=30000&retries=1&manualexecution=N&manualurl=2&myhost=http%3A%2F%2Fgs-rest-feature-test-****.org&mycontextroot=%2F`

But in the execution report, it is not the manual url that is used. The manualHost don't override the url configured by default. I don't understand why. 

Do you have an idea ?

Rémi.

Cerberus3.7.1-1359

**Comment by GrandjeanRemi** [comment]
I find the problem today.

With the step "call service" the host url is not overrided by the property "manualUrl" but with the step "open url with base" it works fine.

Can you fix that please ?

**Comment by vertigo17** [comment]
Can you detail what you put on application environment and on datalib ? In case the url in datalib does not start by http or https or ftp, the url defined at application level should be inserted before the service url where you can leave only the relative url.

**Comment by GrandjeanRemi** [comment]
@vertigo17 

Application environment : 
![image](https://user-images.githubusercontent.com/36671939/44264879-8513f480-a224-11e8-87d8-4f59706d814c.png)

Datalib : 

![image](https://user-images.githubusercontent.com/36671939/44264966-dfad5080-a224-11e8-9d07-3c918dc2b383.png)

**Comment by vertigo17** [comment]
I checked and in fact I managed to have it working correctly.

Definition of Application:
![screenshot_20180826_211216](https://user-images.githubusercontent.com/5342048/44632052-cc148f00-a974-11e8-817e-6cfc49ecee33.png)
points to http://localhost:8080/

Definition of Test Case:
![screenshot_20180826_211047](https://user-images.githubusercontent.com/5342048/44632065-ec444e00-a974-11e8-963c-4482986f45d0.png)
Action callService

Definition of service:
![screenshot_20180826_211110](https://user-images.githubusercontent.com/5342048/44632061-ddf63200-a974-11e8-8188-e7f7d21630d6.png)
Only has the relative URL

Defintion of RunTestCase:
![screenshot_20180826_210957](https://user-images.githubusercontent.com/5342048/44632078-172ea200-a975-11e8-8e6e-e00866280678.png)
Forcing to http://localhost:8181/

When test execute I get the feedback:
![screenshot_20180826_210908](https://user-images.githubusercontent.com/5342048/44632088-3c231500-a975-11e8-82fc-b5f4ae3d43bc.png)
With:
![screenshot_20180826_210926](https://user-images.githubusercontent.com/5342048/44632093-4218f600-a975-11e8-9975-f829137eabab.png)
The Test takes the value from ManualURL.

In order to be able to make that test, I realised that there were a 500 error on AddToExecutionQueueV003 Servlet when environment was not feed with manualurl parameter set to 1.
I fixed and I guess the way you are calling the servlet may not be correct.

Can you provide the way you trigger the execution in order to confirm it comes from that ?

This is what should be used:
![image](https://user-images.githubusercontent.com/5342048/44632174-b56f3780-a976-11e8-928c-58c6b588e7dc.png)

manualurl set to 1 (or 2)
no environment defined.

**Comment by GrandjeanRemi** [comment]
Hello @vertigo17 

I run my campaign from jenkins not from the cerberus interface;

And when i look the call, manualurl  parameter  is at 2 not 1. From jenkins i don't know how pass this parameter at 1.

`Trigger Cerberus call : https://cerberus.preprod.subsidia.org/Cerberus/AddToExecutionQueueV003 with query String : campaign=GS-REST&tag=GS-REST-55&environment=RE7&robot=SeleniumPreprod&screenshot=1&verbose=1&pagesource=1&seleniumlog=1&timeout=30000&retries=1&manualexecution=N&manualurl=2&myhost=http%3A%2F%2Fgs-rest-feature-test-4.traefik-*****.org`
