### ISSUE TITLE
Can execute campaign with several technologie type (selenium / appium / sikuli / ...) - Queue Dependency

### ISSUE THREAD

**Issue by C-L-Marques** [cerberustesting/cerberus-source#1827]
Hello,

I suggest the creation of a new tab on Cerberus Campaigns definition to define dependencies  to be executed after the end of a campaign.

It would be very useful, for example:
- to execute another Cerberus Campaign with similar tag, 
- to open an URL  like http:// ... /Cerberus/AddToExecutionQueueV003?& ...
- Run scripts on command line
- Run Power shell scripts
- Etc. ...

I have this need on VOL_Regression_Tests_A and B campaigns:
"A" tests create several orders. 
After sometime, "B" tests confirm expected behavior.

Best regards,
Carlos Marques

Cerberus Version : 3.8-SNAPSHOT-1359

**Comment by vertigo17** [comment]
What I can suggest is to allow a long and rich description tab on the campaign where you can define free text in the format you like.

**Comment by ffazendeiro** [comment]
Hi,
I believe the ideia is to be possible to execute some scripts before and/or after the Campaign execution (for example at the end of one campaign launch another - linked campaigns):
![image](https://user-images.githubusercontent.com/17747042/45638244-8b57f380-baa4-11e8-9b66-04dbe2b1d662.png)
The drop down could have predefined values (such as "Launch campaign", "Execute test case", ...).
Not sure how this can be implemented (especially the before campaign that should have some kind of reply/trigger so Cerberus knows when Campaign can be executed...).

**Comment by vertigo17** [comment]
I had more in mind a generic long description on which you can format whatever you need.
In long term, the things to do after and before campaign should be added to campaign by improving dependencies on queue management.

**Comment by C-L-Marques** [comment]
I'm not sure that if we have explained this subject by the best way.
But, i will try to explain our particular requirements.

What we want to do is: 
1) Run Cerberus "A" Campaign to Generate 200 Orders
2) Run Cerberus "B" Campaign to validate the correct execution of a Spring Batch

Spring Batch treatment considere all the existants orders at one time.

We can´t include the Spring Batch Validation in Cerberus "A" Campaign because we can´t use 200 Cerberus workers.

If we have, for example, 10 workers; we will need 20 Spring Batch Executions to treat all the 200 Orders.
It will take too much time.

At this moment, we solve the problem, waiting some time before the "B" campaign launch.

In the future we wan't to progrid to "Continuous Integration" and we don´t know how to solve this.

Can you help us, please?

Thanks,
Carlos

**Comment by vertigo17** [comment]
For that purpose what is in the roadmap is called 'Queue Dependency improvements'.
That would mean that you couls link the B testcase to A + the SpringBatch event.
A single Campaign could contain all 200 testcases.
A testcases would execute first (as they have no dependency).
Then you would call the CreateEvent API with the corresponding Tag reference and Event name.
The B testcase would then be automaticly released.
Under the full description.
Does that fit the need ?

## Description

Dependency on :
* other testcase
 I can link a testcase B with a testcase A so that incase they are executed on the same tag, B will not trigger until A is finished.
* wait for event
 I can link a testcase with a specific 'event' so that the testcase will not be triggered until the event is produced. Event can be produced by calling a public service sending the event name + the corresponding tag.
 
## Benefit
* Allow single campaign for batch executions.
* Allow multi application tests scenarii.

**Comment by C-L-Marques** [comment]
Good news. 
It will fit perfectly our need and will open up a range of new solutions.
Thanks

**Comment by nicodeur** [comment]
Issue steps : 

[] Add a new attribute `type` (GUI / APK / IPA / etc) on robot
[] On execution, queued can choose automatically which robot to use for the test case
[] Add possiblity on a Test case to ass a constraint : `must be execute after <test_case>`

**Comment by nicodeur** [comment]
I close this issue. This feature is officially support since Cerberus 4.0. Open a new issue if you find a bug about it
