### ISSUE TITLE
Implement notification using instant messaging (like Slack)

### ISSUE THREAD

**Issue by bcivel** [cerberustesting/cerberus-source#1836]
Especially for the campaign notification, it could be useful to notify using instant messaging (through API).
The best could be to give the choice between SMTP , Instant Messaging or Both.
Thanks

**Comment by vertigo17** [comment]
Issue fixed with new slack connector that will become available in next 3.9 release.

Notification when Campaign start:

![screenshot_20181027_135215](https://user-images.githubusercontent.com/5342048/47616610-a2382f80-dabf-11e8-85d1-8814b34e38e3.png)

Notification At the end of the Campaign execution:

![screenshot_20181027_135232](https://user-images.githubusercontent.com/5342048/47616611-a2d0c600-dabf-11e8-9e39-76a108f53c8f.png)
