### ISSUE TITLE
Issue on "cerberus_queueexecution_defaultrobothost_threadpoolsize" parameter

### ISSUE THREAD

**Issue by Galand-V** [cerberustesting/cerberus-source#1855]
Hello, 

I want to change the global constraint for my Selenium Grid. So I filled the parameter "cerberus_queueexecution_defaultrobothost_threadpoolsize". 
=> It did not worked (I do not see the repercution on the "Pool Follow Up" tab. 

![image](https://user-images.githubusercontent.com/29098010/46014437-83fd9f00-c0cf-11e8-9f1d-a0c1b300ccc8.png)

I noticed the description of this parameter "Default number of simultaneous execution allowed for Robot host constrain (only used when host entry does not exist in invariant table)."

I checked and the only ROBOTHOST invariant was a "localhost" host entered by default.

**Comment by vertigo17** [comment]
Can you confirm that setting the constraint at ROBOTHOST level fix the issue ?
Can you also confirm if this is only the display on the queue followup page that is not correct or if the constrain is not taken into account and more than 17 executions are sent on a single robot host at the same time ?

NB : Even if this could be a bug, this is not a good idea to play with that value to setup a specific constrain on a robot infra.

**Comment by Galand-V** [comment]
Yes, the ROBOTHOST settings fixed the parameter. 

This not just the display that is not correct. The fonction itself has not been applied. TestCases where added to our Selenium grid even if the the pool was full. That managed to overload our grid and crashed it. 

Why do you consider this use as a bad practice ? 
I thought it was the entire goal of this parameter

**Comment by vertigo17** [comment]
Because this is supposed to be a default value in case you have no constrain defined at ROBOTHOST level.
If you change that parameter without creating a specific constrain on that host. the day you have a new robot infra with different constrain you won't be able to tune the 2 constrain at 2 different levels at the same time.
In theory the default value should be closer to what a default selenium hub is able to support (3 to 4 executions). 
Anyway, we will fix the issue.
