### ISSUE TITLE
SSL handshake error on HTTPS REST API call

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-source#1858]
Hi,

When calling an HTTPS REST API I get the following error:

![screenshot from 2018-09-27 21-30-45](https://user-images.githubusercontent.com/1511715/46169940-b7d9ef80-c29c-11e8-985e-bc5933930705.png)

I tried with several public HTTPS API (from [here](https://github.com/toddmotto/public-apis)), as the [StarWars demo API](https://swapi.co/) or the [Chuck Norris Fact demo API](https://api.chucknorris.io/) and I'm getting the same result.

Note that I'm using the Cerberus Docker composition with latest Docker images (Cerberus 3.7.1).

PS: Nice job guys, Cerberus has improved a lot!

Regards,
Aurélien

**Comment by vertigo17** [comment]
Hello Aurélien, first thing to try is to activate the parameter cerberus_accept_unsigned_ssl_certificate to Y in order to be less restrictive with external SSL certificate.
If still not working, you probably need to import the remove certificate to tomcat application server by using the following procedure:

https://github.com/cerberustesting/cerberus-source/tree/master/docs/SSLCalls

On my side I was able to make a call to Starwars demo API without importing the certificate but activating the parameter.

![image](https://user-images.githubusercontent.com/5342048/51430265-de8baf80-1c18-11e9-9773-ac67d28e538f.png)
