### ISSUE TITLE
When create an User the mail isn't send to new user, and the QA fail to reload user-info

### ISSUE THREAD

**Issue by cDelage** [cerberustesting/cerberus-source#1879]
When create an User the mail isn't send to new user, and the QA fail to reload user-info
![image](https://user-images.githubusercontent.com/42372508/47351894-387fe600-d6b9-11e8-9dc6-dfd170e5498c.png)

**Comment by vertigo17** [comment]
I was not able to reproduce.
I created a user with no issue and the mail was received.
I then change the smtp parameters in order to force a fail on email sending and got:
![image](https://user-images.githubusercontent.com/5342048/47873230-ed7c7600-de10-11e8-87b3-c7c982e0b6f6.png)

Please detail the precise use case.
