### ISSUE TITLE
A campaign cannot be launched manually when a test case contains an automated step.

### ISSUE THREAD

**Issue by hananema** [cerberustesting/cerberus-source#1889]
This only happens since 05/11/2018. Before that, we could launch a campaign manually even if it contains totally or partially automated test cases. 
I use partially automated test cases because, as a manual tester, I sometimes use automated steps in libraries to make it easier to automate the test case later.

![image](https://user-images.githubusercontent.com/41586025/48052182-93c8d280-e1a7-11e8-8bd3-d91ea208b4e0.png)

**Comment by vertigo17** [comment]
Does it works when you feed a robot ?
Even if the Execution is manual, this is better to specify a robot as it contain the configuration that must be used in order to perform the test (OS, browser or device, version,....).
If you don't need to specify all that create a generic robot in order to submit that campaign.

**Comment by vertigo17** [comment]
Yes, you should (of course, as long as the test is IPA, APK GUI or FAT (require to define on which OS/broswer config the test needs to be executed).
You can add it to campaign definition to avoid selecting it on the screen.
