### ISSUE TITLE
Create a new application

### ISSUE THREAD

**Issue by qlevert** [cerberustesting/cerberus-source#1897]
Hello,

When I tried to create a new application on Cerberus 3.8, I had this error : 
![image](https://user-images.githubusercontent.com/44800518/48258247-ef4bc800-e414-11e8-9fe0-8b3b0111852c.png)

I have no duplicates and when I tried to add a new application

I tried to add new country and I had the same problem.
Thanks in advance.

**Comment by vertigo17** [comment]
Agree that message is not clear ;-) but what happens there is that you try to create a couple Env+Country on an application where it was not created before at system level.
Go to environment menu in order to create the combination on the system that own the application first.
That will fix the issue.

**Comment by qlevert** [comment]
Thank you ! The problem has been solved

**Comment by glassalle59** [comment]
You miss me ! :D
