### ISSUE TITLE
properties with the same name in imported steps

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#1907]
Hi, 
if we have two diferent imported steps into a testcase and they have a property with the same name but diferent content, wich one is considered for the testcase? 

step xpto1 with property ACCOUNT getfromdatalib C_WEB
step xpto2 with property ACCOUNT getfromdatalib C_WEB_GLOBALE

my testcase uses the xpto2 step first but it's the ACCOUNT from xpto1 that i'ts calculated. 

would it be possible to consider the property used by the first step?

**Comment by vertigo17** [comment]
I added a test case:
https://prod.cerberus-testing.org/TestCaseScript.jsp?test=ENGINE%20:%20Property&testcase=0009A

that trigger this testcase:
https://prod.cerberus-testing.org/TestCaseScript.jsp?test=ENGINE%20:%20Property&testcase=0009B

that has 2 used step STEP1 and STEP2 that have the same PROP1 defined with resp VAL1 from STEP1 and VAL2 from STEP2.

The testcase shows that result is pointing so far to VAL2.

Before I do the change to VAL1, can you confirm that the testcase correspond to what you mean ?
If not can you amend it to reflect the expected behaviour ?
