### ISSUE TITLE
[Enhancement] Add a page to schedule campaign execution (cronjob)

### ISSUE THREAD

**Issue by ahuet67** [cerberustesting/cerberus-source#1932]
**Needs**

I have several users who want to do a supervision on their applications. For that, they want to trigger one campaign per application of their choice each days.

**How to solve it**

**With the API**

My first thought was to use the API to do it. However, it implies to create a DB to store the user perferences, a server to run the cronjobs, the code to call the cerberus api, create a user interface and a login page to secure all of this.

As you can see it’s heavy knowing that cerberus has already a DB, a server to run the cronjobs, a user interface and a login page. Moreover it is for the same application so it would includes understanding difficulties for users  and for a new maintainer.

**With cerberus**

We could create a new page maybe in the run part ? called « schedule campaign execution».
**_In this page, It would at least includes :_**

-	The list of cronjob already running with the possibility to delete it
-	A form to create a cronjob with the possibility to select the campaign we want to trigger.

**_As a nice to have :_**
-	For the list of cronjob, the possibility to disable/enable it without having to delete it and recreate it again and again
-	Including in the form the date/hour when we want to execute the campaign.

Do you agree with that ? If yes, can we do it ?
Thank you for your work !

**Comment by vertigo17** [comment]
Yes, this is for sure a great idea and feature.

A new table will have to support that definition with
-name of the sheduled job
-name of the campaign
-tracability fields
-activation flag.

We first need to find a java lib in order to support the scheduling definition at runtime (we today use spring that does not seem to support that).
Maybe http://cron-parser.com/ and https://github.com/jmrozanec/cron-utils-scheduler could help us on that.

Have you already implemented features on Cerberus ? do you already know any Cerberus core developper who could help you on that implementation that is not an easy one ;-).

**Comment by ahuet67** [comment]
Hi Vertigo,

Ok perfect!
No I never implemented any feature on Cerberus. Maybe @nicodeur can help me if I have some difficulties?

**Comment by ahuet67** [comment]
Hi Vertigo,

Ok Perfect!
I've never implemented any feature on Cerberus. Nevertheless @nicodeur is ok to help me.
So, let's work 😄 
You can assign me to this issue 😉

**Comment by nicodeur** [comment]
Nice, thanks a lot for your proposition @ahuet67

**Comment by vertigo17** [comment]
Let's start by defining the database model.
I propose a new table

**scheduledcampaign**

Columns:
**ID** --> Autoincrement
**Campaign** (FK) --> Campaign to schedule
**CronDefinition** --> definition of the cron schedule
**Active** --> Y in order to activate N to disable
**LastExecution** --> Timestamp of the last job triggered
**LastExecutionMessage** --> output of the execution job (ex nb of exe submited)
**Tracability Fields** (timestamps and users)

If fine with table structure, I will insert the SQL and we will be able to proceed with the Entity/factory/DAO and Services.
Maybe before that we could make a prototype on sheduling implementation based on attached library. For me this is important as it could have an impact on database model (mainly on CronDefinition column).

**Comment by ahuet67** [comment]
Why not true/false for Active state?
What do you mean by Tracability Fields? 
Owner of the cronjob?  Creation date?

In both of the library you suggested, I don't see where they trigger the cronjobs.
In [http://cron-parser.com/](url) there is no "execute" or "run" methods in the cron object.
In [https://github.com/jmrozanec/cron-utils-scheduler](url) in Job.java, he has a "run" method which triggers "execute()" but from where comes this method, I don't know haha

We should test first you're right!

**Comment by cDelage** [comment]
I have search a java library, Quartz seems to me a good solution, 
if no one has already progress on topic, i will make a prototype soon. @ahuet67 what is your advancement on the subject?

**Comment by ahuet67** [comment]
I have not advanced as much as I wanted, not enough time nowadays... I'm still at environment installation x)
You can go for it, maybe next time for me! Thank you very much for your investments

**Comment by cDelage** [comment]
@vertigo17  LastExecutionMessage --> output of the execution job (ex nb of exe submited)
are you sure this field is coherent?
this data does not make sense in this table for me,
But i think tracability will be better if we make 2 fields for it : creator and creationDate (for respect the normal form)
What did you think about it ?

**Comment by vertigo17** [comment]
Work started on the subject:
https://github.com/cerberustesting/cerberus-source/commit/29383cdb4788fda380de002a3aa5c8e9a50aa324

**Comment by vertigo17** [comment]
Feature ready in qa. Will be official in 4.2
Quartz cron expression can be added to campaign modal. 
List of all scheduled campaign with next run execution time can be seen in cerberus monitoring page
