### ISSUE TITLE
BUG: Test field with a suspicious value

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#1939]
Hello,
 
What I did: 
- Create a test ("dlprm-computeappointment")
- Create a testcase in this test
![image](https://user-images.githubusercontent.com/30227758/52469266-49cb0080-2b8b-11e9-970b-e5cfd4eed627.png)

- Create another testcase
![image](https://user-images.githubusercontent.com/30227758/52469302-5baca380-2b8b-11e9-97cb-f1327e9e873a.png)

![image](https://user-images.githubusercontent.com/30227758/52469332-69fabf80-2b8b-11e9-8732-866fef6c4411.png)

As you can see, it automatically set the Test value to the previous description one.

**Comment by vertigo17** [comment]
We also need to prevent the users to create a testcase with empty value for test.
The way the fix is done is that anytime you reorder the columns, the test information is not feed. Either, we control it is not empty, either, we pick the 1st value, either we pick the right column from testcase list page.

**Comment by Nouxx** [comment]
I agree.

I think that if the columns are reordered, we need to fill the Test field (when creating a new tc) with the first raw Test value now matter where it is placed.

**Comment by cDelage** [comment]
This issue is cover by : GUI : Test Management - 0065A
