### ISSUE TITLE
Add the possibilities to put group of label for campaign filter

### ISSUE THREAD

**Issue by mflorid** [cerberustesting/cerberus-source#1953]
Currently when we create a campaign we can put multiple filter on label. 
For exemple campaign TOTO is filter with Label A and Label B. So here my campaign will launched tests with the Label A and the tests with the Label B and the tests with Label A and Label B

But i can't put a filter which take only tests with Label A **and** Label B. This can be an issue when you got 2 applicativ who can have the same fonctionnal feature.

**Comment by Nouxx** [comment]
I agree! The current workaround would be to create as many labels as you need and assign one of them for each campaign.

Keep in mind you can also use Sticker / Requirements labels for selection, if your feature is correclty labeled in your test cases

**Comment by vertigo17** [comment]
Can you provide a concrete example of that use case ?

I would expect a campaign to cover a list of feature (each of them linked with a tag). 
That campaign should include any testcase that has one of those tag assigned (ie using at least one any of the feature defined)
Having a campaign that have both would need to multiply the campaign to have all possible combinations covered. That for me should be avoided. 
Allowing the user to choose between ‘or´ or ´and’ would make interface more complex to manage and potentially confuse some users with unnecessary complexity. 
Please provide an example in order to see if it is worth the extra complexity.

**Comment by mflorid** [comment]
We can see and exemple : take a label "ProductPage" and "addToCart"

If i want to take only test which cover addToCart Fonctionality on the product page, curently i have to add a new label. Because if i put both label in my campagne filter than i will take also test which are not supposed to be in my campaign

**Comment by vertigo17** [comment]
In that case, this is better to create the new label « addToCart2 » and isolate at testcase level the tests that are « addToCart » (from product page) from the test that are addtocart from other area or application. 
Now that hierarchy is displayed in testcase and label screen that provide better visibility.
