### ISSUE TITLE
Get session id from browserstack

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#1956]
Hi,

Would it be possible to implement something to get session id on browserstack? Would be usefull to identify easily the video for one specific execution.
I've tried something like this but cant do it on cerberus:
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=72483144

(https://github.com/browserstack/webdriverio-browserstack/issues/8)

BR

Cerberus Version : 3.11-1397

**Comment by j0hnsa** [comment]
Not necessary anymore, seen on capabilities documentation:

name  - Allows the user to specify an identifier for the test run. | Example: logintest

setting this as %system.EXECID% and we can find it easily:
![image](https://user-images.githubusercontent.com/16339891/54764999-a8ef4c80-4bf0-11e9-8fac-609b2059f690.png)

BR

**Comment by vertigo17** [comment]
I still think that would be good to retreive the external id in order to allow user to get access to it directly from Cerberus.
Let's keep it open.

**Comment by vertigo17** [comment]
New buttons in order to redirect to Browserstack execution 
From here:
![image](https://user-images.githubusercontent.com/5342048/62966417-4862e500-be07-11e9-860d-16e4120f54a2.png)

And here:
![image](https://user-images.githubusercontent.com/5342048/62966447-5a448800-be07-11e9-8db8-5e85ae24620e.png)

To BrowserStack (where executions are grouped by Tag):
![image](https://user-images.githubusercontent.com/5342048/62966482-70eadf00-be07-11e9-94e8-8f64b649301d.png)

New buttons in order to redirect to Kobiton execution 
From here:
![image](https://user-images.githubusercontent.com/5342048/62966530-82cc8200-be07-11e9-9310-58be8f964947.png)

To here:
![image](https://user-images.githubusercontent.com/5342048/62966583-95df5200-be07-11e9-933b-dc4358dc01d4.png)
