### ISSUE TITLE
[BUG] No tests on Parents labelID (Sticker, Requirement , Battery)

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#1962]
Cerberus Version : Cerberus3.12-SNAPSHOT-1397

**Steps** :

1) Create a label parent with children 
![image](https://user-images.githubusercontent.com/33724879/55629879-99f1c800-57b4-11e9-95a5-0d329a3d420d.png)

2) Add some tests on children  labelID

3) Check tests on Parent labelID

![image](https://user-images.githubusercontent.com/33724879/55629996-e3421780-57b4-11e9-97a9-2a9c3925ffe0.png)

**Current result**: No tests are present. It's the same case on the campaign menu when selection label

**Expected result**: The Parents labelID contains all tests of their children labelID

**Comment by Nouxx** [comment]
Currently, as you said, adding a child label doesn't add its parent.

I'm using parent label only to order my sub labels in my reports like this

![image](https://user-images.githubusercontent.com/30227758/55634809-8566fd00-57bf-11e9-99a9-1473cf358df7.png)

I'm not adding my parent label in any test case since I'm only interessted by viewing the child one.

If you want to add automaticaly all the parent label(s), I think we have to discuss the display and how to let the user configure it

**Comment by glassalle59** [comment]
If you want to execute All Tests on Label Payment Type, there will be 0 tests executed. You need to add all the children label in order to execute all the tests ...

**Comment by Nouxx** [comment]
That would make no sense in my situation but I understand your need !
