### ISSUE TITLE
Manual Host and Manual ContextRoot

### ISSUE THREAD

**Issue by mbessa** [cerberustesting/cerberus-source#1981]
Hello,

With last version we aren't no longer able to override Manual Host and Manual ContextRoot via Jenkins plugin or manually.
Can you please check this issue?

Request:
_Trigger Cerberus call : http://cerberus.siege.red/Cerberus/AddToExecutionQueueV003 with query String : campaign=CI_iofr-getservice&tag=iofr-getservice_PROD1_20190520161221&environment=PROD&browser=firefox&screenshot=0&verbose=0&pagesource=0&seleniumlog=1&timeout=20000&retries=1&manualexecution=N&manualurl=2&myhost=http%3A%2F%2Fapp231.siege.red%3A8010&mycontextroot=%2Fiofr-getservice%2F_

Execution not overridden:
_Error on CallREST : org.apache.http.conn.ConnectTimeoutException: Connect to vipiofr.siege.red:443_ 
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=75421648

Please let me know if you need more information.

Cerberus Version : 4.0-1400

**Comment by vertigo17** [comment]
Since last release, myhost parameter takes multiple application values with format:
appli1:url1;apli2:url2
As a consequence, you cannot use : and ; characters inside url.
Can you try removing http:// from the myhost parameter.
I will try to support http:// and https:// in the parsing to allow more flexibility but we will probably have to review the format of that parameter.
