### ISSUE TITLE
Issus on Cerberus Tomcat

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#2017]
Cerberus Version : 4.1-1419

I've installed Cerberus Tomcat with docker-compose file on a VM. I have some issues on it.
Indeed, every day (random appear) the cerberus database maintenance database is displayed and I must restart docker to no longer have it.

Can you help me plz ?

**Comment by vertigo17** [comment]
Not sure that there is a correct fix for that as this is due to the mysql docker that stops after a idle period. Once stop, the connection from tomcat docker is lost and Cerberus beleive that the database is empty.
One way you can try is to configure parameter cerberus_automaticqueuecancellationjob_period to 5 (minutes). By default it is set to 60.
Putting the parameter to 5 will trigger an SQL every 5 minutes and even if it will do nothing, it may force the database to stay up.
