### ISSUE TITLE
Changed the name of a testfolder that had TC with dependencies

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-source#2039]
Hello,

There was a situation where a user changed the name of a testfolder that contained tc with dependencies among them and now its impossible to delete or add new TC dependencies of this folders. Can you try to fix this issue to avoid future occurrences?

Best Regards 

Cerberus Version : 4.2-1438

**Comment by vertigo17** [comment]
Well I could not reproduce. Please detail the use case.

This is the one I did:
1/ create 2 testcases from testcase page: test / testcase1 and test / testcase2
2/ from testcase screen, on test / testcase2, added dependency to test / testcase1
3/ from test page, renamed test to test1
4/ reopen test1 / testcase2 and saw that dep was correctly pointing to test1 / testcase1
I could from that modal create new dependencies with no problems.

Not sure how that can be possible as there is a database integrity in order to secure that testfolder name change apply to all database.

**Comment by j0hnsa** [comment]
Hi @vertigo17 

Found the problem actually was the name of the folder that was creating this problem. If the name contains "( )" it'll make impossible to add/remove dependencies.
