### ISSUE TITLE
Add field "Project" to test case header

### ISSUE THREAD

**Issue by ffazendeiro** [cerberustesting/cerberus-source#2046]
Hi,
Field "Project" is still present on table testcase, page /Project.jsp is still active and field is present on the page /TestCaseList.jsp filters but the field is no longer present on the test case header (and therefor cannot be changed/added or removed).
Would it be possible to add it again on the test case header?
This field is very helpful to keep track of some test case creation purposes (adding back this field would avoid create sticker to identify project and is transversal to all systems).
Thank in advance.

**Comment by R-Loic** [comment]
Hello Filipe,

We removed that field because it was redundant with the labels. The idea is to simplify the GUI so the project will no longer be available and won't be present in the new GUI.

**Comment by vertigo17** [comment]
I removed availability of project data from the GUI to be more consistent.
Data is still in database.

**Comment by vertigo17** [comment]
Filipe, I close the issue as we will not fix it but maybe we can do an automatic script to convert the projects to Labels in order to migrate the data in case it has been used.
Please reopen the issue if you think this is worth building those scripts.
1 script could create the necessary Labels in database attached to a parent label (I guess Battery or requirement is the best choice).
Another one to create the links with all testcases.

**Comment by dcop7** [comment]
Hello,
This projects are still used for builds. We have a new project that we want to associate with a build, but we can't add this new project.
Can you readd the projects GUI only for builds?
