### ISSUE TITLE
Run a manual test without robot

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2051]
Hello,

Can we skip the robot verification (GUI, APK, IPA application) in the run page when we are launching a testcase on manual mode.

![image](https://user-images.githubusercontent.com/30227758/70045778-f962da80-15c4-11ea-8718-3c69ebd094de.png)

I have to select any robot (since my application is GUI) even if it will not be used 

Thanks

**Comment by vertigo17** [comment]
Well in fact, even if the execution is manual, you may need to specify on which browser and OS you want to execute it. You could even specify several robots in order to perform manual tests on various browser.
I will remove the restriction but a better option should be to create generic robot that specify the expected environnment used to perform the manual test.

**Comment by Nouxx** [comment]
I agree, but if the users want to make use of that feature, they will select the corresponding robot.
Having this restriction was a proven blocking point for the manual users that only want to launch the tests right away on a ENV/COUNTRY!
