### ISSUE TITLE
goog:chromeOptions capabilities

### ISSUE THREAD

**Issue by remi-dandois** [cerberustesting/cerberus-source#2069]
I need to use specific chromeOptions in my tests executions.
I tried to set these options in robot capabilities, but they are not present in the "finalCapbilities" 
exemple: 
![image](https://user-images.githubusercontent.com/54069464/72264191-967c4e80-361a-11ea-8a01-7b7db6a16a82.png)
 this is really similar to : https://github.com/cerberustesting/cerberus-source/issues/1828, but with "goog:chromeOptions" capability.

I had the same result in Cerberus 3.9-1388 and 4.3-1440
Best regards

**Comment by vertigo17** [comment]
Thanks Remy, today, Cerberus generate automatically the goog:chromeOptions capability in order to force fullscreen at start (and also potentialy activate headless mode).
I will check if we can bypass that when the capability is defined at robot level (in order to allow the users to put his own).

**Comment by vertigo17** [comment]
Unfortunately the goog:chromeOptions capability is not created by Cerberus but feeded from arguments list passed to ChromeOptions options = new ChromeOptions();
As a consequence, maybe this is safer either to 
1/ add a list of text arguments value that will be added at that stage. (problem is that it will be Chrome only as firefox require key/value format)
2/ add a checkbox in order to active the trust to unsecured certificates. That would both set the capability but also argument automaticly for both firefox and chrome.

If the only need is to trust unsecured certificates, option 2/ is probably the most user friendly option. 

Can you confirm this is the only missing Options so that we can rename issue to trust unsecured certificates for both Firefox and Chrome ?

**Comment by remi-dandois** [comment]
Hello Vertigo,
the above screenshot was only for example purpose. I need multiple values to customize as goog:chromeOptions. 
The firs solution will be the best one for chrome navigator.

**Comment by vertigo17** [comment]
Solved on 4.14
