### ISSUE TITLE
[REG] Passed tests are not displayed on Report by Tag

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-source#2115]
Since 4.6, when a test is passed, it is not longer displayed on Report by Tag

TEST FA : displayed

![image](https://user-images.githubusercontent.com/33724879/77112000-a17aa300-69fe-11ea-8d69-ccdd17a1702c.png)

TEST OK : not displayed

![image](https://user-images.githubusercontent.com/33724879/77112093-c707ac80-69fe-11ea-809f-425ca3c0690a.png)

**Comment by vertigo17** [comment]
This is not a regression but a feature.
Since 4.5, Cerberus no longer display execution where lines are all OK.

Extract from changelog:
_**ReportByTag now only display Test Case that require some analysis to be done (ie : are not fully OK or QU or have a bugId defined at test case level). That avoid display lines where nothing needs to be analyzed. That can be changed with a flag near the refresh button.**_

You can still display them by checking 'Full List' and press refresh.

That allow to speed up drastically the page loading on large campaigns.
