### ISSUE TITLE
Cerberus Extension with Selenium Grid : IP Management

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2133]
Hello,

Considering this situation, we're using a Selenium Grid with several execution nodes. All of the node (grid + slaves) have Cerberus Executor installed. 

The Cerberus Executor is configured like this:
![image](https://user-images.githubusercontent.com/30227758/83731570-0d0dfd00-a64b-11ea-8eea-daa15632aecb.png)

We'd like to use for the Executor Extension Host, the ip of the execution node that will be returned by the grid.

Leaving the field empty or providing a variable (such as %system.SELENIUM_NODE%) could be very nice ! 

![image](https://user-images.githubusercontent.com/30227758/83732092-d97fa280-a64b-11ea-8d45-7bc38b2b7973.png)

**Comment by vertigo17** [comment]
I checked what could be done on Selenium side and fear that we will have restrictions.
In fact, proxy is defined by setting capabilities. On selenium, unfortunatly, capabilities cannot be changed once the selenium session has been created. And Node Ip can be retreived only once the session has been created.
As a consequence, when session is created, we don't have the node IP yet and once we have it we can no longuer change the proxy setting using capabilities because session is already created.

I fear that we can't do much better than having proxy service executed on the hub IP and secure the memory size will support all necessary executions.

What we still can do is to add an extra queue constrain managed by public invariant (just like ROBOTHOST) in order to secure a maximum of parallel executions on an executor host.

we would name the new invariant EXECUTORHOST, adding autocompletion on it and using attribut 1 in order to configure the max allow // execution on it. That will allow to secure we don't over stress the proxy service with too much execution and still maximizing more execution on the same hub if proxy service is not activated.

**Comment by Nouxx** [comment]
I agree 👍

**Comment by vertigo17** [comment]
I called it EXECUTOREXTENSIONHOST.
