### ISSUE TITLE
Campaign timeout parameter not used

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#2135]
Cerberus Version : 4.8-SNAPSHOT-1491

Hello,
when launching an android campaign with a 15 s timeout parameter : 

![image](https://user-images.githubusercontent.com/995694/84006949-e6fc9b80-a96f-11ea-8230-c07f2963b2c7.png)

Also, with a 20s wait element parameter set @ system : 

![image](https://user-images.githubusercontent.com/995694/84008185-c5041880-a971-11ea-8859-d8c185db8051.png)

The execution wait 60s during ifElementPresent (i dont find a 60s parameter)

![image](https://user-images.githubusercontent.com/995694/84008280-e7963180-a971-11ea-85f4-e891387a61dd.png)

Execution : http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=99046966

If you need any more information, ask me, 

thanks for your help !

**Comment by vertigo17** [comment]
It should be fixed.
Please reopen if test is not conclusive.

**Comment by vitoo** [comment]
@vertigo17 fix in PR #2138

**Comment by vitoo** [comment]
@vertigo17 ca marche dans le cas ou je fais un click, ça utilise bien le appium_wait_element

par contre si je fais un ifElementPresent, ça utilise le  cerberus_selenium_wait_element	

![image](https://user-images.githubusercontent.com/995694/85874136-727c8600-b7d2-11ea-8afb-67b553201c0c.png)

**Comment by vertigo17** [comment]
That should be now fine.
I created some tests to secure regression on those use cases:
For Click
https://prod.cerberus-testing.org/TestCaseScript.jsp?test=ENGINE%20%3A%20Action&testcase=0015A
For Wait
https://prod.cerberus-testing.org/TestCaseScript.jsp?test=ENGINE%20%3A%20Action&testcase=0017A
For IfElementPresent
https://prod.cerberus-testing.org/TestCaseScript.jsp?test=ENGINE%20%3A%20Action&testcase=0028A

Feel free to add more in order to secure them.

**Comment by vitoo** [comment]
in cerberus 4.8, its still waiting 300 seconds

![image](https://user-images.githubusercontent.com/995694/88530333-80a40900-d001-11ea-9436-7385241c0124.png)

**Comment by vitoo** [comment]
update : the wait is OK in cerberus QA  version 4.9
