### ISSUE TITLE
Condition blocking the manual execution

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2161]
Hello,

I'm trying to launch a test case that contains a step with a condition (verifyElementVisible) **manually** but I'm getting this error :

![image](https://user-images.githubusercontent.com/30227758/90015679-34b3be00-dca9-11ea-9d9a-8f4b29e6b428.png)

It doesn't make sense to me.

Can make this behave like there is no condition as a first step?

As a second step, I'd be great to handle the condition in a better way. We already brought this topic: #1861

_Cerberus4.7-1491_

**Comment by Nouxx** [comment]
I'm launching my test case on type APK Application and it's trigger with conditions 'IfElementVisible'

**Comment by MorganLmd** [comment]
@Nouxx I have finished implementing this feature, you can test it on QA env. Since you told me you would do the TNR yesterday, I'll let you do that. 
Right now 6 conditions are available for manual execution :
- ifElementPresent
- ifElementNotPresent
- ifElementVisible
- ifElementNotVisible
- ifTextInElement
- ifTextNotInElement

An information message with the condition that needs to be evaluated is added to the step/action/control description

**Comment by Nouxx** [comment]
Feature covered by test case: [ENGINE : Action / 0031A](https://prod.cerberus-testing.com/TestCaseScript.jsp?test=ENGINE%20:%20Action&testcase=0031A)
