### ISSUE TITLE
[Feature request] Campaign notification email by country 

### ISSUE THREAD

**Issue by vitoo** [cerberustesting/cerberus-source#2165]
Hello,

Marc Ernoult would need (for Web Perf project) dynamic campaign notification email filtered by country 

Example: at the end of campaign, RU manager receive an email notification with filtered RU tests result 

Do you think its possible ?

Thanks

**Comment by vertigo17** [comment]
Preco is to split the campaign in order to notify on different distribution list (and also define diferent country scope).
Adding that notification rule at campaign level will make campaign config too complex (the rule could also be per BROWSER or ENVIRONMENT which would make config even more complex.).
