### ISSUE TITLE
Data Menu is Missing

### ISSUE THREAD

**Issue by DrArmus** [cerberustesting/cerberus-source#2208]
The Data Menu to access the Data Library is missing from our install of 4.10 (since 4.9)

It is also missing from the Cerberus Demo Site.

![cerberusdata](https://user-images.githubusercontent.com/4846426/98734867-d35ec200-235f-11eb-8a03-bd1f240f8874.PNG)

Is this intentional? Trying to learn how to setup a Data Library and saw that the Documentation and Interactive Tutorial refer to it.

**Comment by vertigo17** [comment]
No this is not intentional ;-).
Looks like when adding tutorial, we cleaned some code on the menu and fixed an issue where TestData menu entry was shown even if user did not have the role TestDataManager.
I fixed demo by adding the TestDataManager role to admin user. Check that your user has that role in order to get access that menu entry.

**Comment by DrArmus** [comment]
Awesome! Thank you! Looks like that role wasn't in the GetKeycloakImport?realm=Cerberus json we imported to key cloak. Added it manually, all good now!

**Comment by vertigo17** [comment]
Just added the missing role inside the GetKeycloakImport service. Thanks for mentioning it.
