### ISSUE TITLE
Can't click on the 'Apply Next SQL' button

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2210]
Pulling the latest version and from a fresh new database, the `Apply next SQL` button is disabled

![image](https://user-images.githubusercontent.com/30227758/99259696-a9534700-281a-11eb-8b19-b8f510ed747c.png)

I'm getting theses error from the console:

![image](https://user-images.githubusercontent.com/30227758/99259639-98a2d100-281a-11eb-968f-33442f45ee0d.png)

It is possibly linked to new development?

**Comment by Nouxx** [comment]
Removing the disabled attribute from DOM allows me to work this around

**Comment by vertigo17** [comment]
I could not reproduce the issue.

I dropped the database and open directly the database page:
http://localhost:8080/Cerberus/DatabaseMaintenance.jsp
I could reach the end of the database update and the button was always available.

![image](https://user-images.githubusercontent.com/5342048/100324114-07282180-2fc7-11eb-9677-c07151ee3f8d.png)

I dropped again the database and this time open:
http://localhost:8080/Cerberus/
Then login (using Keycloack)
Answer the message to update the database and then init the database just like above still without any issue.

Can you test again and detail how to reproduce.
Maybe it was fixed with @MorganLmd fix ?

**Comment by Nouxx** [comment]
I was able to reproduce in the docker developer environment added in a7c2dae87a4967a4445c8cac7d412d300179c504

**Comment by Nouxx** [comment]
closed with #2223
