### ISSUE TITLE
Notification Cerberus onTeams 

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-source#2216]
Hello everybody, 

Currently, Cerberus is able to notify Slack. We would like to have this notification on teams. 
do you think it's possible ? 

Thank you 
peggy (LaRedoute)

![image](https://user-images.githubusercontent.com/29864420/100279512-f942b400-2f66-11eb-8a33-4eabce4d3e9e.png)

**Comment by vertigo17** [comment]
From what I could investigate, every channel has a specific email attached.
As a consequence, that should be as simple as adding that channel email to the distribution list of email.
I would be interested to have a feedback if it works this way ;-)

**Comment by MowglieRed** [comment]
Olà, i'm having a look. and  i keep you up to date.

**Comment by vitoo** [comment]
For what i've seen its like for Slack, an http webhook  

https://techcommunity.microsoft.com/t5/microsoft-teams/microsoft-teams-incoming-webhook-message-formatting/m-p/31984

**Comment by vertigo17** [comment]
Digging on the link above I collected those ressources:

Simulator to preview the results:
https://messagecardplayground.azurewebsites.net/

```
{
	"@type": "MessageCard",
	"@context": "https://schema.org/extensions",
	"themeColor": "0078D7",
	"title": "Execution Tag 'Cerberus.20210104-035643' Ended.",
    "summary": "238 Execution(s) - 238 OK - 0 KO - 0 FA.",
	"sections": [
		{
			"activityTitle": "Campaign successfully Executed. CI Score = 0 < 100",
			"activitySubtitle": "9/13/2016, 11:46am",
			"activityImage": "http://vm.cerberus-testing.org/delivery/img/logo/Logo-cerberus.png",
			"text": "238 Execution(s) - 238 OK - 0 KO - 0 FA."
		}
	],
	"potentialAction": [
		{
			"@type": "OpenUri",
			"name": "View in Cerberus",
			"targets": [
				{
					"os": "default",
					"uri": "https://prod.cerberus-testing.org/ReportingExecutionByTag.jsp?Tag=Cerberus.20210104-035643"
				}
			]
		}
	]
}
```

![image](https://user-images.githubusercontent.com/5342048/103679115-bc65d600-4f84-11eb-9b4f-0052de25b620.png)


```
{
	"@type": "MessageCard",
	"@context": "https://schema.org/extensions",
	"themeColor": "0078D7",
	"title": "Execution Tag 'Cerberus.20201230-035315' Ended.",
	"summary": "238 Execution(s) - 235 OK - 0 KO - 3 FA.",
	"sections": [
		{
			"activityTitle": "Campaign failed. CI Score = 300 >= 100",
			"activitySubtitle": "9/13/2016, 11:46am",
			"activityImage": "http://vm.cerberus-testing.org/delivery/img/logo/Logo-cerberus.png",
			"text": "238 Execution(s) - 235 OK - 0 KO - 3 FA."
		}
	],
	"potentialAction": [
		{
			"@type": "OpenUri",
			"name": "View in Cerberus",
			"targets": [
				{
					"os": "default",
					"uri": "https://prod.cerberus-testing.org/ReportingExecutionByTag.jsp?Tag=Cerberus.20210104-035643"
				}
			]
		}
	]
}
```

![image](https://user-images.githubusercontent.com/5342048/103679240-e5866680-4f84-11eb-991e-9fcafa96be13.png)


More documentation on json format [here](https://docs.microsoft.com/en-us/outlook/actionable-messages/message-card-reference)

In order to activate the webhook: Click on Application tab then serach webhook and select 'incoming webhook'

![image](https://user-images.githubusercontent.com/5342048/103679599-52016580-4f85-11eb-9cd2-48cee33b8b53.png)

Then Add to a team:
![image](https://user-images.githubusercontent.com/5342048/103679738-837a3100-4f85-11eb-8e65-77d1694b9e1e.png)

Then select a team:
![image](https://user-images.githubusercontent.com/5342048/103679786-97be2e00-4f85-11eb-9c4e-c0163f496723.png)

Then Put a name, optionally select a picture and hit create:
![image](https://user-images.githubusercontent.com/5342048/103680095-f8e60180-4f85-11eb-9b0b-c4d69d8435e9.png)

Page will reload allowing you to copy the webhook URL:
![image](https://user-images.githubusercontent.com/5342048/103680197-1915c080-4f86-11eb-980d-b1419590e7bb.png)


We will probably put 2 different logos for sucess and failed.

**Comment by vertigo17** [comment]
This issue will be done with #2050

Just like Slack, we will add a Teams section at campaign level in order to configure the webhook + the 2 flags for start and end of campaign execution configuration.

**Comment by vertigo17** [comment]
Examples on latest dev:

![image](https://user-images.githubusercontent.com/5342048/128414087-c46a6030-f389-412a-846d-80d777c51a93.png)

![image](https://user-images.githubusercontent.com/5342048/128414171-e4d674fa-abe2-4e58-8b80-639e874f5097.png)

![image](https://user-images.githubusercontent.com/5342048/128414287-ef857466-4257-4e29-aefa-915a6b940edc.png)

**Comment by vertigo17** [comment]
![image](https://user-images.githubusercontent.com/5342048/128495960-165df524-4b52-47f1-871e-1e164882bb6c.png)

**Comment by MowglieRed** [comment]
Hello
we are testing with success ! thanks a lot. 
![image](https://user-images.githubusercontent.com/29864420/135639760-623fd88b-1f11-451d-b8be-a816c2a50af7.png)
