### ISSUE TITLE
v4.11.1 ChangePassword.jsp in loop

### ISSUE THREAD

**Issue by paulinedessingue-lm** [cerberustesting/cerberus-source#2229]
Hi Cerberus team,

We noticed abnormal behavior on version 4.11.1 : 
1. Create a new account
2. Login with this new account for the first time with default password
3. Be redirected to the change password page
This page  ChangePassword.jsp is reloading in loop.

Can you help us please ?
Thanks

**Comment by vertigo17** [comment]
Hello Pauline, 
Unfortunatly, CICD only support keycloak configuration ;-(. This is why that issue was not detected ;-(.

Before I release a 4.11.2, can you test again using docker image: cerberustesting/cerberus-as-tomcat:SNAPSHOT
Docker SNAPSHOT tag has been created and will automatically be refreshed after every commit. 
That should allow to test bugfix with less effort right after we perform fix.
