### ISSUE TITLE
(TOO LONG TO DISPLAY !! Please check Action or Property detail) Issue

### ISSUE THREAD

**Issue by C-L-Marques** [cerberustesting/cerberus-source#2233]
Cerberus Version : 4.11.2-1583

With last Cerberus vertion, it's not possible to see the complete "Return Message" sentence on "property value" detail.

Is it possible to, only, display the string "'%.. (TOO LONG TO DISPLAY !! Please check Action or Property detail)%'" on step/properties lists?

The testcasestepactionexecution.ReturnMessage field should, also, preserve all the information.
<img width="550" alt="2021-01-15 15_44_28-Clipboard" src="https://user-images.githubusercontent.com/30627092/104749321-942b6380-574a-11eb-8e3f-6c2f4dbd0e5a.png">

Thanks

**Comment by vertigo17** [comment]
Hello @C-L-Marques ,
Can I ask you what will be that information for ?
This feature was implemented in order to avoid having pages on unusefull information that ends up making the return messages unreadable. 
This truncate is only done on end user messages (for example when a hughe property contain is duplicated inside that return message)
In your particular example, I don’t see what will be the added value on displaying the full message. Wait failed because field was not there. 
I would be interested to see an example where we loose an information that prevent to understand what happened on the execution. 
Worst case I can add a parameter in order to tune the nb of caracter truncate but best is to remove it when it is really important and leave it in order to make UI easier to understand when useless.

**Comment by C-L-Marques** [comment]
Hello vertigo17,

I was using "ReturnMessage" field to retrieve a huge list of products.
I agree that it was not the best way to do this.
I found an more eficient/clean solution.
Please, close this ticket.

Thanks

**Comment by vertigo17** [comment]
Good. This is indeed better to use a clean property in order to get and use the data.
Those messages should only be use to display messages as clean as possible to end users.
