### ISSUE TITLE
Manual execution with looped steps

### ISSUE THREAD

**Issue by Nouxx** [cerberustesting/cerberus-source#2243]
I faced this bizarre behavior while running a manual test with a looped step 

I workarounded it but I don't really know why..

![manualbug](https://user-images.githubusercontent.com/30227758/110978433-acdb8280-8363-11eb-81f2-58a8d0fe7ca7.gif)

We don't have this behavior with no looped steps

Version: Cerberus4.11.2-1583 Build 20210113-073231

**Comment by vertigo17** [comment]
Hello @Nouxx , I was not able to reproduce the issue.
I created a testcase in the video below with loop steps and post test (that also loop)
Maybe you can share the testcase data. Idealy I would need to access your system in order to reproduce and fix ;-).


https://user-images.githubusercontent.com/5342048/118174593-522bd900-b42f-11eb-93f9-c19942d4fbf8.mp4

**Comment by vertigo17** [comment]
Hello @Nouxx any feedback to help reproduce the issue ?

**Comment by vertigo17** [comment]
Hello @Nouxx any feedback to help reproduce the issue ? I need your help to reproduce the issue ;-)

**Comment by Nouxx** [comment]
Hey!
Sorry for the late response, upgrading to 4.11 seemed to solve the issue somehow

**Comment by vertigo17** [comment]
Great !!
