### ISSUE TITLE
Self Healing element path

### ISSUE THREAD

**Issue by vertigo17** [cerberustesting/cerberus-source#2252]
Support erratum algorithm that will allow to remove the need to adapt xpath to changing html page content.
That will reduce maintenance effort of xpath.

**Comment by vertigo17** [comment]
Just a couple of explanation on how it works :

For every action, elements can now be defined with a new syntax:

`erratum=<FullXPathValue>,<html source that correspond to the full XPath taken>
`


ex:

`erratum=/html/body/button,<!DOCTYPE html> <html>     <head>         <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">         <title>JSP Page</title>         <script type="text/javascript" src="../dependencies/jQuery-2.2.3/jquery-2.2.3.min.js"></script>              </head>     <body>                  <button id="erratumButton">Errratum</button>     </body> </html>`


Chrome console can be used in order to collect both xpath and html source

After pointing to element, Xpath can be retreived from Elements tab:
![image](https://user-images.githubusercontent.com/5342048/119039066-24f1a480-b9b4-11eb-89ba-c0f84435e681.png)


HTML source retrieved on the same tab selecting on the top html level:
![image](https://user-images.githubusercontent.com/5342048/119039203-42bf0980-b9b4-11eb-8c6e-1ab628107a46.png)

A Chrome extention will be developped in order to copy the complete syntax in a single step.

**Comment by fchaabani** [comment]
Hello,
I tried to test Erratum in QA & UAT with reflex interface and I have always the same error message:
"Failed to wait because Erratum could not match the element on new page ! That can happen if page is too different from the original one."

I tested with two different pages:

First one that is the same and does not change

Second one the elements IDs changes after each page load.
And for both cases Cerberus return the same error message.

PS: this is the syntax that I used to identify the element:
erratum=/html/body/div[4]/div/input[1],<input name="user" type="text" class="a-logininput" placeholder="Nom d'utilisateur">

Where fullXpath = /html/body/div[4]/div/input[1]
and outerHTML = <input name="user" type="text" class="a-logininput" placeholder="Nom d'utilisateur"

I noticed also that after the execution, Cerberus changed the element identification to:

![image](https://user-images.githubusercontent.com/33456029/120769533-84f05b00-c51d-11eb-8235-71eae4d0ad46.png)


Thanks,
Regards,

**Comment by lssol** [comment]
Bonjour,
Merci pour le retour.
Serait-il possible d'avoir acces aux urls ou a l'HTML des pages en question (originale et evolution) ?

Merci.

**Comment by vertigo17** [comment]
@fchaabani , you need to put the complete html of the full page not an extract of it. 
it must include the top level (html)

regards the second point after each save, cerberus hide the full html code in order to secure the UI response time.

**Comment by vertigo17** [comment]
Will be in 4.12
