### ISSUE TITLE
I don't find the robot host or port information in the "EXECUTIONS IN QUEUE" screen of a campaign 

### ISSUE THREAD

**Issue by Vastraa** [cerberustesting/cerberus-source#2286]
On the Cerberus 4.11.2-1583 Build 20210113-073231
I have some schedule mobile campaign with several tests on OK and several other on FA
When I go on the detail of the schedule campaign
I scroll down to the "List" block
I click on the "Open Queue" button
I'm redirected to the screen "Execution in Queue"
On the table, the column "Robot host" & "Robot port" are empty ( see screen )
![Capture](https://user-images.githubusercontent.com/82046243/130212940-e23b0b57-e8f0-47ad-b3d2-e41aca38e87f.PNG)
Whereas when I go on the "Robot" menu of the "execution detail" of one of my test ( OK or FA ) I got the robot port and robot host informations.

**Comment by vertigo17** [comment]
Hello @Vastraa ,
In fact this is 'normal' and I will explain you why ;-).
When you submit a new execution on Cerberus it first create a queue entry and leave it there in a QUEUED state.
When resources are available, Cerberus submit the execution and it is only at that time that the robot host and port are calculated. 
When the execution is in queue, we don't know yet on which robot executor it will be triggered. If you defined more than 1 executor for the robot, Cerberus could pick one or another depending on the constrains defined and robot executor usage.

Probably you will wonder why the robot host and port are available at queue level on that screen.
The reason is that Cerberus allow you to submit an execution without any robot defined. In that case, you can pass directly the host, port and also browser on the execution screen. Only in that case, the host and port will be defined at queue level if you submit your execution against a robot, only the robot information will be defined.

In summary, the information available at queue level correspond to the parameters that you asked Cerberus when submitting your execution and in your case you defined the robot but no host and no port so at queue level you have the robot defined but no host neither port.
At execution level you will have what really happened during the execution (including the choices Cerberus has taken). Real host and port will be defined here (and you will even have the nodes one and not the hub that just route the execution).

When execution is finished, this is better not to feed those 2 data because in case you want to submit it again you not not want Cerberus to force the execution on that host but still on the robot that may pick another executor. If I update the queue entry with that data, resubmiting the execution will force it on that host and port.

Hope those explanations are clear ;-).
Please confirm if this is clear.

**Comment by Vastraa** [comment]
Hello @vertigo17 ,

Thanks you for your explanation it's much more clear :)

**Comment by vertigo17** [comment]
Ok so I close the issue ;-)
Please enrich it and I will reopen if this prevent from doing a specific use case.
