### ISSUE TITLE
KeyPress not working properly in SAP web environment

### ISSUE THREAD

**Issue by SBO-ADEO** [cerberustesting/cerberus-source#2337]
Hello, 

I am trying to use Left Arrow, F6 and other keys in a SAP web based environment but this is not giving any results.
Can you please check out this problem to let me know how to move from one field to another using arrows.

Thank you

**Comment by vertigo17** [comment]
Hello to all. Issue was linked to SAP not supporting Keypress done from Selenium.
In order to solve the issue we used hybrid mode (including sikuli feature on Selenium node) and forced keypress action in sikuli mode putting picture= inside 1st field and then putting Key.TAB on key to press.

![image](https://user-images.githubusercontent.com/5342048/165380919-cdf798f7-1971-4473-8b94-73dd8f1d2a6f.png)
