### ISSUE TITLE
[LR] Rename a Campaign

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-source#2352]
Hello :)
Currently we can't directly update the name of a campaign in Cerberus.
We have to create a new one, which is impratical.

Thanks.
Aurélien Ioossen - LR
![image](https://user-images.githubusercontent.com/97182913/150147897-42896aa1-4477-4bf9-8a5a-ddd4ec6e242a.png)

**Comment by vertigo17** [comment]
This is an improvement we could do.
The only limitation / warning is that campaign name are probably used on CICD systems in order to trigger campaigns. If we allow to rename it easily in Cerberus, it may not be that easy to rename it on external system that reference it. Due to that it may not be a good idea to rename a campaign.
