### ISSUE TITLE
Impossible to delete application objects

### ISSUE THREAD

**Issue by RoydDevs** [cerberustesting/cerberus-source#2363]
Hi,
I wanted to delete an application object because I wanted to change his name but I can't. 
When I try to delete one, an error message appears : 
![CerberusBugDeleteAppObjects](https://user-images.githubusercontent.com/51986543/155342962-db171d16-ddc1-4584-827d-13f1d9bd317a.gif)

I replicate with all objects of my application.

Mathieu SIRERE - La Redoute

**Comment by vertigo17** [comment]
Issue was fixed from 4.12
https://prod.cerberus-testing.com/documentation/D2/documentation_en.html#_4_12

Please confirm the version you use.

**Comment by RoydDevs** [comment]
![image](https://user-images.githubusercontent.com/51986543/155508811-09b7a4a0-8f6e-4d21-a51c-5932084bba5f.png)

I am from La Redoute, it seems to be the 4.12 version.

**Comment by vertigo17** [comment]
The fix was done here:
https://github.com/cerberustesting/cerberus-source/commit/76b2d8b5f0bcaca7c5b899c1813123a4963d94eb

This is strange as it was comit mid Feb (Feb 14, 2021) and your version seems to be from March, 3rd. It should include it but obviously doesn't!!! I wonder why.

Anyway, I let you upgrade to at least 4.12
