### ISSUE TITLE
SQL Library or Database creation restricted to a system

### ISSUE THREAD

**Issue by ping0uin** [cerberustesting/cerberus-source#2384]
Hi.
We are experiencing a use case which is using the SQL Libraries.

The Database availability is not restricted to a system. 

<img width="570" alt="Capture d’écran 2022-05-06 à 14 53 44" src="https://user-images.githubusercontent.com/14962879/167135258-5a996c08-79aa-49d8-b4d9-ce40ed84add3.png">

That means that everybody can use it, and perform requests on the database. Even if we can create a read only restricted user on the database, especially for cerberus tests, it still an internal security breach for us. The accessible data must be restricted in our case.

Is that possible to condition the database or the SQL Library creation to a system, and don't propose it in the select box if you're not in the right system?

**Comment by vertigo17** [comment]
Indeed, PROPERTYDATABASE Invariant is available across all application.
But you can only access to that database from a test case if that database has been configured to the right jdbc ressource path at environment level.
Even if you select that database on a testcase or a datalib, you will not access to the jdbc ressource if an allowed user configure that ressource on the given environment.

If other words: If the following line on environment definition is not created:
![image](https://user-images.githubusercontent.com/5342048/167712495-10b02cdb-f925-48f4-a999-b742397a9852.png)

No access to that database will be available on FR / PREPROD.
And in order to add that line, you need an access to that system.

BTW, The key information that needs to be secured in order to prevent your users on different system to use access they are not allowed is the **jdbc ressource string**. One way to secure that is to randomize a part of the name so that noone can guess the name and access to it adding that configuration on its system.
