### ISSUE TITLE
Run Multiple Tests from previous Run

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#748]
Would it be possible to add a button to a ExecutionByTag that would run all the tests in the same tag? 
For example here http://192.168.134.35/Cerberus/ReportingExecutionByTag.jsp?Tag=OMNITURE_2016050212 the user would click in a "rerun multiple tests" button that would automactily choose/fill all the tests under the same tag/environments/countries ? 
Thanks!

**Comment by vertigo17** [comment]
What can be done is to allow the tag criteria to  filter a list of testcases from run page.
Keeping the detail of every country, environment for each execution seems too heavy.
On top of that the target is to use campaing in order to be able to start a batch of execution in one click from the GUI (or a service).

**Comment by ruirpr** [comment]
Well, if the a list of testcases can be filled from tag, would also be helpfull in some cases. Thanks

**Comment by vertigo17** [comment]
For me that feature is available on the last version with 'Submit Again' button.
The only part that maybe missing is the select all combo but not sure this is really needed to rerun on the same tag if the execution was OK.
Please reopen and enrich if you feel that would be necessary.

![screenshot_20171112_201845](https://user-images.githubusercontent.com/5342048/32702384-bae3d850-c7e6-11e7-9e19-10941e4e09ee.png)
