### ISSUE TITLE
new feature // multi browser / tab navigation

### ISSUE THREAD

**Issue by pfoucray** [cerberustesting/cerberus-source#771]
Cerberus Version : 1.1.4-SNAPSHOT

Hi,
here's an execution report (only available to Cerberus Admin) that shows we can almost do multiple window/tab navigation.
1) Screenshot shows it didn't change tab
2) KO confirms it didn't change tab
Probably something to dig in cerberus.
http://192.168.134.35/Cerberus/ExecutionDetail.jsp?id_tc=32399629

Also, I used a javascript technik to get to that result
OPEN NEW WINDOW / TAB :
Cerberus action : calculate property. OPEN. "OPEN" property = getFromJS
function OpenInNewTab(url) {
 var win = window.open(url, '_blank')
 win.focus();
}
return OpenInNewTab("http://www.google.com")

CLOSE NEW WINDOW / TAB :
Cerberus action : calculate property. CLOSE. "CLOSE" Property = getFromJS
return window.close();

That would be a great + to Cerberus.
1) allow change focus would be a good minimum
2) create actions open new tab / close tab would be a dream :D

Keep up the nice work,
regards,
PF

**Comment by vertigo17** [comment]
Playing with multiple tabs or wondow on the browser is a bit hazardous in terms of result.
What I can propose is that you stay on the same window but open the Google to do your stuff and then go back to the original application on the same session.
What we could do in order to hard code URL in testcase and have it linked on the application / environment is to create some generic variables at that level that could be reused in the test with %SYS_APP_VAR1% %SYS_APP_VAR2% %SYS_APP_VAR3% etc.
You could then make any contextual calls to any other site still configured dnamically for each environment on a given application.
Could that fit the need ?

**Comment by pfoucray** [comment]
Well, I'm not quite sure I understand the solution. And if I understand at least a little part ("stay on the same window [...] then go back to the original session")... I'm not sure it'll work in my case.
I'm working on some e-business website. I need to get into some random e-mail adress right in the middle of my purchase to get a code and enter the code in the same basket / session I left to get the code (code is generated by the basket...).
On the other hand, you're talking about sessions... which is precisly what I can't loose at that stage of the purchase.
I'm not sure, I should check first, trying to leave window / tab and come back

**Comment by abourdon** [comment]
@vertigo17, @bcivel : what could we do so?

**Comment by vertigo17** [comment]
Nothing.
For me this is not to implement as it would bring too much complexity (with the risk of making the tool not usable in the long terms).

**Comment by abourdon** [comment]
Ok so we can close it
