### ISSUE TITLE
Refactor GUI : page See Execution in Queue

### ISSUE THREAD

**Issue by vertigo17** [cerberustesting/cerberus-source#784]

**Comment by pfoucray** [comment]
On my version cerberus version (1.1.11-SNAPSHOT-1050) I get that message, when execution are in queue : "DataTables warning: table id=executionsTable - Requested unknown parameter 'comment' for row 0, column 8. For more information about this error, please see http://datatables.net/tn/4."

Which is funny, is that because Db maintenance page is still old page, with old menu, when clicking see execution in queue from that old menu, you land on old execution queue page. And that old page still works without errors (select, delete, etc.)

**Comment by abourdon** [comment]
@pfoucray: already fixed with the current SNAPSHOT version that will be released soon

Regards,
Aurélien
