### ISSUE TITLE
Using xpath Count()

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#863]
Is it possible to get the result from xpath count() in cerberus? 
Example: xpath=count(//*[@data-cerberus='mainmenu-l1-universe'])
Thanks

**Comment by abourdon** [comment]
Hi Rui,

Actually, Cerberus delegates to [Selenium](http://www.seleniumhq.org/) to execute XPath expression on a Webpage. And the particularity of Selenium is to only get nodes from a XPath expression, and not a value as your example.

In order to execute XPath on a webpage, we could use the [Java XPath implementation](https://docs.oracle.com/javase/7/docs/api/javax/xml/xpath/package-summary.html), but this one needs to load the entire DOM page and can be long if DOM is huge. To tackle this performance issue, we could use the [Java SAX parser](https://docs.oracle.com/javase/7/docs/api/javax/xml/parsers/SAXParser.html), but this one cannot be natively used with XPath.

One solution could be to use other libraries, as those listed from the following SO: http://stackoverflow.com/questions/1863250/is-there-any-xpath-processor-for-sax-model.

We will test them and go back to you.

Regards,
Aurélien

**Comment by abourdon** [comment]
After testing most of them, we noticed two major issues:
- HTML syntax has to be strictly correct, which is (sadly...) not the case for most of HTML documents 
- Parsing takes long time to be done.

Now, just looking at your issue. You want to compute the number of nodes that can be retrieved from your underlined XPath. What about add option from the getFromHtml property type in order to get node count? Or an other new property type?

@bcivel, @vertigo17, please let me know

**Comment by vertigo17** [comment]
What about getting the result from a getFromJS ?

**Comment by ruirpr** [comment]
Yes, currently i'm using getFromJS with:
```

var count = document.evaluate("count(//div[@class='right-panel']//*[@data-cerberus='lnk_plpProduit-category1'])", document, null, XPathResult.NUMBER_TYPE, null);
count = count.numberValue;
return count;
```

It works fine.

**Comment by vertigo17** [comment]
This is the best way to do it.
I close the issue.
