### ISSUE TITLE
verifyElementPresent / verifyElementNotPresent time to execute

### ISSUE THREAD

**Issue by ruirpr** [cerberustesting/cerberus-source#899]
Hi, 
it is really necessary to take so long to do these actions? 
I understand it takes the defacult selenium_defaultWait value but could it stop when OK? Otherwise, some tests can take too long to execute. 

Thanks, 
Rui

**Comment by bcivel** [comment]
Hi @ruirpr 
Just to be sure I understand. Today, it works like that : 
- verifyElementPresent >> Wait the defaultWait before returning KO, return OK as soon as element found.
- verifyElementNotPresent >> Wait the defaultWait before returning OK, return KO as soon as element found.

What you expect is : 
- verifyElementPresent >> Keep it like today.
- verifyElementNotPresent >> Return OK if elementNotPresent (Beware it can be too quick than you can have false OK if bad usage). Wait the defaultWait before returning KO if element is present.

Am I right?

**Comment by pfoucray** [comment]
I have the same comment : today it makes no sense in most cases to have a long timeout for "verifyElementNotPresent".
Say you're on a classic website, testing with selenium. You load a page, and want to confirm an element is not present. Unless it's asynchrone, cerberus will wait for the page to load, and then wait another time, while elementNotPresent should instantly be detected.

What would be awsome, would be to be able to set a timeout for each action / control. So that you can judge by yourselfe atm you implement your TC :)

So :
- Keep the default timeout for global Testcase
- put a specific one if you want to, for specific actions !

**Comment by ruirpr** [comment]
Regarding the verifyElementPresent it should give OK as soon as the element is found? It looks like it waits the defaultWait for both KO and OK.

**Comment by ruirpr** [comment]
Notice this execution http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=40315730

verifyElementNotPresent took almost 6 minutes to complete and it was only sucessuful because i refreshed the page;

**Comment by MichaelWil** [comment]
Hi,
I fully understand the risk of checking that an element is not present while if the page is not loaded  the test will be ok as we don't know anything about what is going to happen (the element will be present or not).

My idea is to build the test that way :
1- you check that the page is fully loaded (putting a wait for some seconds or better you make a control to check if another element is present and if it's the case it should mean : "if this element is present then it means that the whole page is loaded")
 2- Once you are sure that the page is fully load you ask Selenium to check that the element you want is not present. As soon as the control is done once it entails the end of the test.

Although checking that an element is not present is not an habit, do you think we can act that way ?

**Comment by bcivel** [comment]
Hi @ruirpr , @MichaelWil, 
I changed the verifyElementNotPresent to work like that : 
 - It Wait the defaultWait before returning KO if element is present.
 - It Return OK if elementNotPresent (Beware it can be too quick than you can have false OK if bad usage). 

So it's the exact opposite of verifyElementPresent as requested

**Comment by MichaelWil** [comment]
Hi @bcivel,

Thanks for your update.
I understand the risk of using this action and i'll make an communication to the all test team to make sure they are all aware of that too.

Thanks again !

**Comment by ruirpr** [comment]
Sorry but something is not quite right, i never asked for this: "It Wait the defaultWait before returning KO if element is present." - i think it was sugested by @bcivel and to me it does not make sense. verifyElementNotPresent should give KO as soon as element is present.

the original problem was: every action was taking too long, verifyElementNotPresent and verifyElementPresent, element present or not as described before and example given in http://cerberus.siege.red/Cerberus/ExecutionDetail.jsp?id_tc=40315730 (6 minutes to give OK)

@MichaelWil the test team is already aware of the situation, thanks!

**Comment by gmoita** [comment]
From my point of view, this is how it should work:
1) verifyElementPresent should give KO only if element is not found within the specified timeout (should wait until timeout exceeded)
2) verifyElementPresent should give OK if element is found within the specified timeout (as soon as element is found, should stop waiting)
3) verifyElementNotPresent should give KO as soon as  element is found within the specified timeout (should continue to next step as soon as element is found)
4) verifyElementNotPresent should give OK if element is not found within the specified timeout and page has finished to load; otherwise, it should give a FA

For an element to be not present, page must be fully loaded (that is my point of view).

**Comment by bcivel** [comment]
Thanks for your feedback. I agree with you for the behavior of the verifyElementPresent. 

For the verifyElementNotPresent (which have similar behavior than verifyElementNotVisible and verifyElementNotClickable), I think the opposite. I think we should not wait until the end of a timeout before delivering an OK status. The OK status is what we target, so we try until we get a OK, and if the timeout is reached, we raise a KO.

Anyway, verifying the page is loaded won't give you any interresting information. Today, most of the time, the element are modified asynchroneously through ajax request and from the browser point of view, the page is fully loaded.

Don't hesitate to re-open the ticket again if you're not convinced. At least, we can wait a couple of days more until we get more feedback.
