### ISSUE TITLE
Cerberus deletes properties when renaming

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-source#955]
Hello,

If you create a property "toto" then save. and after you rename it with "TOTO" the property will disappear !

Thank you

Cerberus Version : 1.1.6-SNAPSHOT

**Comment by abourdon** [comment]
Due to several reasons:

- When updating properties, insertion is done before deletion.
- In addition: Cerberus MySQL character comparison is case insensitive because using the default `utf8_general_ci` character collation.
- When inserting TOTO with existing toto, then an exception is threw by JDBC but not raised to caller.

But I think this is an old behaviour when looking at code...
Then several questions (@bcivel @vertigo17):

- Should properties be case sensitive?
- Is it normal to always compare characters by using case insensitive comparison by default? (Not only scoped to `testcasecountryproperties` table but all Cerberus tables and columns).
- From not only `TestCaseCountryPropertiesDAO` but a lot of DAOs: is it normal to have the `throwExcep` variable only used to throw 'business' exception and not technical ones as constraint breaking?
Due to several reasons:

- When updating properties, insertion is done before deletion.
- In addition: Cerberus MySQL character comparison is case insensitive because using the default `utf8_general_ci` character collation.
- When inserting TOTO with existing toto, then an exception is threw by JDBC but not raised to caller.

But I think this is an old behaviour when looking at code...
Then several questions (@bcivel @vertigo17):

- Should properties be case sensitive?
- Is it normal to always compare characters by using case insensitive comparison by default? (Not only scoped to `testcasecountryproperties` table but all Cerberus tables and columns).
- From not only `TestCaseCountryPropertiesDAO` but a lot of DAOs: is it normal to have the `throwExcep` variable only used to throw 'business' exception and not technical ones as constraint breaking?

**Comment by bcivel** [comment]
From the bottom to the top:

- throwExcep is the old way to raise error to the business. It should not be used anymore (and testcase is more or less the last page where it is).
- As case insensitive is defined in the database, it's coherent to have it in the code too.
- So, properties cannot be case sensitive.

**Comment by abourdon** [comment]
Not able to reproduce right now
